<div class="single-work-page renewal">
    <div class="single-work-page__container _container">
        <div class="_grid-2-col">
            <div class="empty"></div>
            <h1 class="single-work-page__title _page-title">Vodafone</h1>
        </div>
        <section class="single-work-page__top single-work-top">
            <div class="single-work-top__body _grid-2-col">
                <div class="single-work-top__label _section-label ">
                    <a href="" class="single-work-top__link"></a>
                </div>
                <div>
                    <div>
                        <h5 class="single-work-top__text single-work-page__description">Vodafone online store is an online platform of the leading mobile operator Vodafone Ukraine, which serves more than 19
                            million subscribers. The company is committed to providing customers with an equal opportunity to access technology and the latest mobile services. </h5>
                    </div>
                    <ul class="services-list">
                        <li class="mb-0"><a href="">Web Design</a></li>
                        <li class="mb-0"><a href="">Magento Development</a></li>
                        <li class="mb-0"><a href="">Magento Security Audit</a></li>
                        <li class="mb-0"><a href="">Server & Magento Optimization</a></li>
                    </ul>
                </div>
            </div>
            <div class="single-work-page__image single-work-page__image--w-full">
                <picture>
                    <source  srcset="https://m2perspective.test/media/wysiwyg/works/vodafone/industry_mob.png" media="(max-width: 767px)" />
                    <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/industry.jpg" alt="Vodafone online store top" />
                </picture>
            </div>
        </section>
        <section class="single-work-page__tech _grid-2-col">
            <!-- section label -->
            <div class="_section-label flex items-center" itemprop="keywords">Key technologies</div>
            <!-- content (span 2) -->
            <div class="single-work-page__technologies">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/magento.svg" alt="magento">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/google-analytics.svg" alt="google-analytics">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/google-search-console.svg" alt="google-search-console">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/pay-pal.svg" alt="pay-pal">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/hyva.svg" alt="hyva">
            </div>
        </section>
        <section class="single-work-page__goals single-work-goals">
            <div class="single-work-goals__body _grid-2-col">
                <div class="single-work-goals__label _section-label">Goals</div>
                <div class="service-single__content service-single__content--wide">
                    <h2 class="h3 single-work-goals__title single-work-section__title" itemprop="name">The main task</h2>
                    <div class="text-2col">
                        <div>
                            <p class="mb-16">
                                The company developed very quickly, increasing the volume of visitors and sales. More and more products, services and offers for
                                customers appeared that needed to be organically displayed in the online store.
                            </p>
                            <p class="mb-16 mb-md-0">
                                The design of the working website did not correspond to the scale of the company and looked outdated. A fresh look at the
                                interface and design was required, without losing brand recognition.
                            </p>
                        </div>
                        <ul class="_list">
                            <li>To develop an online store for the leading mobile operator Vodafone Ukraine</li>
                            <li>Make a convenient filter by technical parameters and characteristics;</li>
                            <li>Add sorting by availability in stores;</li>
                            <li class="mb-0">Create a personal account where regular customers can view their purchase history.</li>
                        </ul>
                    </div>
                </div>

            </div>
        </section>
        <section class="single-work-page__results single-work-results">
            <div class="single-work-goals__body _grid-3-col">
                <div class="single-work-goals__label _section-label">Results</div>
                <div class="single-work-goals__col">
                    <h3 class="single-work-goals__title h3 single-work-section__title">What we did</h3>
                    <div>
                        <p class="mb-16">
                            The following pages have been developed: checkout, catalog, menu (4 levels for 130 + thousand products) also
                            a header and a footer, product card with all states.
                        </p>
                        <p class="mb-16">
                            We collected user experience across all pages, as well as customer feedback, and made changes promptly.
                        </p>
                        <p class="mb-0">
                            In addition, we have developed a mobile version of the site, which meets all the requirements of the user experience.
                        </p>
                    </div>
                </div>
                <div class="single-work-goals__col">
                    <div class="result-squares">
                        <div class="result-squares__square">
                            <div class="result-squares__number">+57%</div>
                            <h5 class="h5 result-squares__text">Revenue</h5>
                        </div>

                        <div class="result-squares__square">
                            <div class="result-squares__number">+24%</div>
                            <h5 class="h5 result-squares__text">Conversion Rate</h5>
                        </div>

                        <div class="result-squares__square">
                            <div class="result-squares__number">-46%</div>
                            <h5 class="h5 result-squares__text">Page Speed</h5>
                        </div>

                        <div class="result-squares__square">
                            <div class="result-squares__number">4</div>
                            <h5 class="h5 result-squares__text">Years of Support</h5>
                        </div>
                    </div>
                </div>
            </div>
            <div class="single-work-page__image single-work-page__image--w-full single-work-page__video single-work-page__video--w-full">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vodafon-video-placeholder.jpg" alt="Vodafone online store video placeholder" loading="lazy"></picture>            </div>
        </section>
        <section class="single-work-page__homepage single-work-homepage">
            <div class="single-work-homepage__body _grid-3-col">
                <div class="single-work-homepage__label _section-label">Homepage</div>

                <div class="single-work-homepage__content single-work-homepage__content--wide">
                    <h3 class="single-work-homepage__title h3 single-work-section__title">Homepage is the <br /> soul of a brand</h3>
                    <p class="single-work-homepage__text content-shortened">Home page is an important navigation element. Thanks to the home page, users can go to the required section and in which case
                        always return to the "starting point". And this is especially felt when visiting a store from a mobile device, when the menu is not so clear and it is the main one that is used to go to the desired section.</p>

                    <ul class="single-work-homepage__list single-work-homepage__list--cols _list">
                        <li class="mb-8">
                            <div class=" _list__legend">Header</div>
                            <p>Logo, contacts, menu, search, cart, favorites, product comparison; authorization</p>
                        </li>

                        <li class="mb-8">
                            <div class=" _list__legend">Main screen</div>
                            <p>The ability to make changes in the basket itself</p>
                        </li>

                        <li class="mb-8">
                            <div class=" _list__legend">Bestsellers</div>
                            <p>hot offers, promotional products, new positions or those positions that are bought most often</p>
                        </li>

                        <li class="mb-8">
                            <div class=" _list__legend">Blog</div>
                            <p>The ability to make changes in the basket itself</p>
                        </li>

                        <li class="mb-8">
                            <div class=" _list__legend">Loyalty block</div>
                            <p>The ability to make changes in the basket itself</p>
                        </li>

                        <li class="mb-8">
                            <div class=" _list__legend">Footer</div>
                            <p>hot offers, promotional products, new positions or those positions that are bought most often</p>
                        </li>
                    </ul>

                </div>

                <div class="single-work-homepage__content single-work-homepage__content--second">
                    <h3 class="single-work-homepage__title h3 single-work-section__title">Elasticsearch</h3>
                    <p class="single-work-homepage__text">Convert searches to sales with Elastic Search. Instantly show customers the most relevant search results, helping them find what they're looking for faster.</p>
                    <ul class="single-work-homepage__list _list">
                        <li class="mb-8">
                            <p>Full-text and multilingual search throughout the site</p>
                        </li>
                        <li class="mb-8">
                            <p>Partial search by SKU, title, attribute or category</p>
                        </li>
                        <li class="mb-8">
                            <p>Autocomplete options and typo fixes</p>
                        </li>
                        <li class="mb-8">
                            <p>Add alternative search terms and words to ignore</p>
                        </li>
                        <li class="mb-8">
                            <p>Optimized for all devices.</p>
                        </li>
                    </ul>
                </div>

                <div class="single-work-homepage__content single-work-homepage__content--third">
                    <h3 class="single-work-homepage__title h3 single-work-section__title">Mega menu</h3>
                    <p class="single-work-homepage__text">We have improved the quality of customer service by providing fast and flexible access to all pages of the online store. Expand the possibilities of your store by creating an attractive and dynamic navigation menu.</p>
                    <ul class="single-work-homepage__list _list">
                        <li>
                            <p>Provided smooth navigation on mobile</p>
                        </li>
                        <li>
                            <p>Added CMS blocks, images, products, brands and links to your menu</p>
                        </li>
                        <li>
                            <p>Set up detailed or accordion menu mode.</p>
                        </li>
                    </ul>
                </div>

                <div class="single-work-page__image single-work-page__image--w-full single-work-homepage__image single-work-homepage__image--first">
                    <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vodafon-homepage-1.png" alt="Vodafone online store homepage screenshot 1" />
                </div>
                <div class="single-work-page__image single-work-page__image--w-full single-work-homepage__image">
                    <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vodafon-homepage-2.png" alt="Vodafone online store homepage screenshot 2" />
                </div>
            </div>
        </section>

        <section class="single-work-page__catalog single-work-catalog">
            <div class="single-work-catalog__body _grid-3-col">
                <div class="single-work-catalog__label _section-label">Catalog</div>

                <div class="single-work-catalog__content">
                    <h3 class="single-work-catalog__title h3 mb-16">Catalog Page</h3>
                    <ul class="single-work-catalog__list single-work-list _list">
                        <li>
                            <div class=" _list__legend">Catalog filtering</div>
                            <p>Ajax + SEO s the perfect mix. Individual for each category.</p>
                            <p>Layered navigation for searching products by category or by attribute. For example, when a shopper chooses the certain category from the top navigation, the initial include all products in the category. The list can be filtered further by choosing a specific style, climate, color, material, pattern, or price—or a combination of values. Filterable attributes appear in an expanding section that lists each attribute value. As an option, the list of products with matching results can be configured to include products with, or without, a match.</p>
                        </li>
                        <li>
                            <div class=" _list__legend">Built-in advertising</div>
                            <p>Banner display management system</p>
                        </li>
                        <li>
                            <div class=" _list__legend">Lots of labels</div>
                            <p>An additional tool for managing visitor attention</p>
                        </li>
                        <li>
                            <div class=" _list__legend">Viewed products</div>
                            <p>Simplifies navigation and increases conversion</p>
                        </li>

                        <li>
                            <div class=" _list__legend">Ajax products uploading</div>
                            <p>In-grid and one-page bulk-update feature</p>
                        </li>
                    </ul>
                </div>

                <div class="single-work-page__image single-work-page__image--w-full single-work-catalog__image">
                    <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-catalog--small.png" alt="Vodafone online store catalog" />
                </div>
            </div>

            <div class="single-work-page__image single-work-page__image--w-full single-work-page__video">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-catalog-vid-placeholder.png" alt="Vodafone online store catalog placeholder" />
            </div>
        </section>

        <section class="single-work-page__product single-work-product">
            <div class="single-work-product__body _grid-2-col">
                <div class="single-work-product__label _section-label">Product page</div>
                <div class="single-work-product__content content-shortened">
                    <h3 class="single-work-product__title h3 single-work-section__title">product pages that motivate shoppers to buy</h3>

                    <div class="single-work-product__text">
                        <p>When designing an online store, a lot of focus goes into the homepage—after all, it’s the first thing visitors see when they arrive. But the real goal of any ecommerce website is sales, and there’s no way you’ll achieve that without stellar product pages</p>
                        <p>Effective product pages immediately convey the value of a featured product. They show potential customers what a product looks like, tell them what it feels like, and make them believe it’s something they absolutely need to own.</p>
                        <p>The product page includes several key elements to help shoppers decide if they want to buy:</p>
                    </div>

                    <ul class="single-work-product__list _list">
                        <li class="mb-6">Short, descriptive product information</li>
                        <li class="mb-6">Recognizable lifestyle images</li>
                        <li class="mb-6">Multiple payment methods</li>
                        <li class="mb-6">Refund and return policy information (30-day returns, 1-year warranty)</li>
                        <li class="mb-6">Shipping policy. Intelligent calculation of delivery time based on the product and buyer location</li>
                        <li class="mb-6">Additional sales. Standard opportunity to increase the check for retail</li>
                        <li class="mb-6">Cheaper together. Multipurpose promotional tool. It is convenient to choose a set for yourself</li>
                        <li class="mb-0">Extended feedback. Stars, voting, answers, hierarchy</li>
                    </ul>

                    <p>Scroll down, though, and a more robust product discovery experience awaits. Graphics that highlight the features, benefits, and materials of each product along with user-generated content in the form of videos give you a deeper dive. </p>
                </div>
            </div>

            <div class="single-work-page__image single-work-page__image--w-full single-work-page__video">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-product-vid-placeholder.png" alt="Vodafone online store video screenshot" />
            </div>
        </section>

        <section class="single-work-page__more single-work-more">
            <div class="single-work-more__body _grid-3-col">
                <div class="single-work-more__label _section-label">More pages</div>
                <div class="single-work-more__col">
                    <h3 class="single-work-product__title h3 mb-16">Portal page </h3>
                    <p class="single-work-more__text">Ability to create a page with a page builder.</p>
                    <div class="single-work-page__image single-work-more__image ">
                        <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-more-1.png" alt="Vodafone online store screenshot 1" />
                    </div>
                </div>
                <div class="single-work-more__col">
                    <h3 class="single-work-product__title h3 mb-16">All promotions</h3>
                    <p class="single-work-more__text">The ability to filter, view products and conditions of the promotion.</p>
                    <div class="single-work-page__image single-work-more__image ">
                        <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-more-2.png" alt="Vodafone online store screenshot 2" />
                    </div>
                </div>
            </div>
        </section>

        <section class="single-work-page__bag single-work-bag">
            <div class="single-work-bag__body _grid-2-col">
                <div class="single-work-bag__label _section-label">Shopping bag</div>
                <div class="single-work-bag__content">
                    <h3 class="single-work-bag__title single-work-section__title">Why shopping carts <br /> are important</h3>
                    <p>Shopping carts bridge the gap between shopping and buying, so having the best shopping cart software is extremely important on your website.</p>
                    <p>For the Vodafon project, we have developed a full-fledged cart page for cross-selling.</p>
                    <p>The main items of the shopping cart:</p>

                    <ol class="single-work-bag__ordered-list ">
                        <li>
                            <div class="_list__legend _list__legend">Product</div>
                            <ul class="_list">
                                <li>Product photo</li>
                                <li>The ability to go to the product card directly from the cart</li>
                                <li>Indicate the size, color and SKU of the product</li>
                                <li>The ability to make changes in the basket itself</li>
                            </ul>
                        </li>
                        <li>
                            <div class="list__legend _list__legend">Bonuses, promotions and promotional codes</div>
                            <ul class=" _list">
                                <li>Complete information on the formation of the total amount of the order</li>
                                <li>The opportunity to cancel the use of bonuses or a promotional code has been given</li>
                                <li>Information about the accrual of bonuses for purchases in the store</li>
                            </ul>
                        </li>
                        <li>
                            <div class="list__legend _list__legend">Information about additional costs</div>
                            <p>Additional costs, for example, delivery of goods.</p>
                        </li>
                        <li>
                            <div class="list__legend _list__legend">Cross-sale and upsell</div>
                            <p>The ability to add related products, additional services or consumables without leaving the cart.</p>
                        </li>
                    </ol>

                    <p>According to statistics, over the past 6 months, 79% of purchases were made from a mobile phone or tablet. Therefore, we focused on developing an online shopping cart for mobile users.</p>
                </div>
            </div>

            <div class="single-work-page__image single-work-more__image ">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-bag.png" alt="Vodafone online store checkout" />
            </div>
        </section>

        <section class="single-work-page__checkout single-work-checkout">
            <div class="single-work-checkout__body _grid-2-col">
                <div class="single-work-checkout__label _section-label">Checkout</div>

                <div class="single-work-checkout__content">
                    <div class="single-work-checkout__cell">
                        <h3 class="single-work-checkout__title single-work-section__title">Effective Checkout Page</h3>
                        <p class="single-work-checkout__text">The checkout developed by us for Vodafon has an attractive design, easy to use, simple, clear, functional and safe.</p>
                        <ul class="single-work-checkout__list _list">
                            <li>
                                <div class="_list__legend _list__legend">Step-by-step checkout</div>
                                <p>We broke the ordering process into four consecutive steps, with the ability to edit the order at any time and, most importantly, that all previously entered data is saved.</p>
                            </li>
                            <li>
                                <div class="_list__legend _list__legend">Authorization by sms</div>
                            </li>
                            <li>
                                <div class="_list__legend _list__legend">Integration with delivery services</div>
                                <p>API communication, as well as user geo-location.</p>
                            </li>
                            <li>
                                <div class="_list__legend _list__legend">Loan mechanics</div>
                                <p>Everything is online, without additional calls and redirects.</p>
                            </li>
                        </ul>
                    </div>

                    <div class="single-work-checkout__cell single-work-checkout__cell--desktop">
                        <div class="single-work-page__image single-work-checkout__image">
                            <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-checkout-1.png" alt="Vodafone online store checkout screenshot 1" />
                        </div>
                    </div>
                    <div class="single-work-checkout__cell single-work-checkout__cell--desktop">
                        <div class="single-work-page__image single-work-checkout__image">
                            <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-checkout-2.png" alt="Vodafone online store checkout screenshot 2" />
                        </div>
                    </div>
                    <div class="single-work-checkout__cell single-work-checkout__cell--desktop">
                        <div class="single-work-page__image single-work-checkout__image">
                            <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-checkout-3.png" alt="Vodafone online store checkout screenshot 3" />
                        </div>
                    </div>

                    <div class="single-work-checkout__cell single-work-checkout__cell--mobile">
                        <div class="single-work-page__image single-work-page__image--w-full">
                            <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-checkout-mob.png" alt="Vodafone online store checkout screenshot 4" />
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="single-work-page__dashboard single-work-dashboard">
            <div class="single-work-dashboard__body _grid-2-col">
                <div class="single-work-dashboard__label _section-label">Dashboard</div>

                <div class="single-work-dashboard__content single-work-dashboard__content--wide">
                    <h3 class="single-work-dashboard__title single-work-section__title">Customer Accounts</h3>
                    <p class="single-work-dashboard__text">A convenient personal account helps to build relationships with regular customers, increases loyalty, stimulates sales and will relieve the support service. To implement the functionality of the account, you need to register as quickly as possible and draw up a number of nuances, which we will consider below.</p>
                </div>

                <div class="single-work-dashboard__content">
                    <ul class="single-work-dashboard__list _list">
                        <li>
                            <div class="_list__legend _list__legend">Order history</div>
                            <p>Storing data on purchases of the user. The shopping list is displayed in a separate tab - the latest orders are shown above. The user can see: order number, date of purchase, quantity of goods, cost and order fulfillment status. Implemented the ability to quickly repeat a purchase</p>

                        </li>
                        <div class="single-work-page__image single-work-dashboard__image single-work-dashboard__image--mobile">
                            <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-dashboard-mob-1.png" alt="Vodafone online store mobile version screenhot 1" />
                        </div>
                        <li>
                            <div class="_list__legend _list__legend">Address management</div>
                            <p>That some online stores offer users to edit the address, while others - to add a new one. We have implemented both possibilities in the interface.</p>

                        </li>
                        <div class="single-work-page__image single-work-dashboard__image single-work-dashboard__image--mobile">
                            <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-dashboard-mob-2.png" alt="Vodafone online store mobile version screenhot 2" />
                        </div>
                    </ul>
                    <ul class="single-work-dashboard__list _list">
                        <li>
                            <div class="_list__legend _list__legend">The "Favorites" functionality</div>
                            <p>If a user has added a product to Favorites, he will most likely return to the site and place an order. We have implemented the functionality of adding a product to the cart directly from "Favorites".</p>

                        </li>
                        <div class="single-work-page__image single-work-dashboard__image single-work-dashboard__image--mobile">
                            <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-dashboard-mob-3.png" alt="Vodafone online store mobile version screenhot 3" />
                        </div>
                        <li>
                            <div class="_list__legend _list__legend">Subscription management</div>
                            <p>Many customers are interested in subscribing to the newsletter to learn about promotions and special offers. It is possible to select the events about which the user wants to be notified.</p>

                        </li>
                        <div class="single-work-page__image single-work-dashboard__image single-work-dashboard__image--mobile">
                            <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-dashboard-mob-4.png" alt="Vodafone online store mobile version screenhot 4" />
                        </div>
                    </ul>
                </div>
            </div>

            <div class="single-work-page__image single-work-dashboard__image single-work-dashboard__image--desktop">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-dashboard-desk.png" alt="Vodafone online store dashboard desk" />
            </div>
        </section>

        <section class="single-work-page__functionality single-work-functionality">
            <div class="single-work-functionality__body _grid-3-col">
                <div class="single-work-functionality__label _section-label">Functional</div>
                <div class="single-work-functionality__col">
                    <h3 class="single-work-functionality__title single-work-section__title">Not visual functionality</h3>
                    <p>Online booking of a workplace in coworking with calculation of cost for each hour. Interactive map with the choice of the necessary place in the hall.</p>
                </div>
                <div class="single-work-functionality__col">
                    <div class="single-work-functionality__cards">
                        <div class="single-work-functionality__card functionality-card">
                            <div class="functionality-card__body">
                                <div class="functionality-card__image ">
                                    <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-functional-1.png" alt="Magento integration with ERP" />
                                </div>
                                <p class="functionality-card__text--bold">Integration with 1C</p>
                            </div>
                        </div>
                        <div class="single-work-functionality__card functionality-card">
                            <div class="functionality-card__body">

                                <div class="functionality-card__image">
                                    <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-functional-2.png" alt="Magento speed optimization" />
                                </div>
                                <p class="functionality-card__text--bold">Download speed optimization</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="single-work-page__adaptive single-work-adaptive">
            <div class="single-work-adaptive__body _grid-2-col">
                <div class="single-work-adaptive__label _section-label">Adaptive</div>

                <div class="single-work-adaptive__content">
                    <h3 class="single-work-adaptive__title single-work-section__title">Ecommerce Goes Mobile</h3>
                    <p class="content-shortened">Of recent years, mobile devices have also become a popular medium for online shopping — and that’s where mobile commerce steps in. Mobile shopping is now possible through mobile optimized websites</p>

                    <div class="single-work-page__content-2-col">
                        <ul class="single-work-adaptive__list _list">
                            <li>
                                <div class="_list__legend _list__legend">Auto-detect user's device</div>
                                <p>The site itself determines from which device the user comes to it, and opens the corresponding version.</p>
                            </li>
                            <li>
                                <div class="_list__legend _list__legend">Minimal Design for fast loading</div>
                                <p>The mobile version does not contain elements that are unnecessary for mobile versions, which speeds up the loading and operation of the site</p>
                            </li>
                        </ul>

                        <ul class="single-work-adaptive__list _list">
                            <li>
                                <div class="_list__legend _list__legend">Usability with touchscreen device</div>
                                <p>The mobile version is not tied to the desktop version code and is limited to make it easier to work on mobile devices</p>
                            </li>
                            <li>
                                <div class="_list__legend _list__legend">Adapted functionality for mobile devices</div>
                            </li>
                        </ul>
                    </div>
                </div>

            </div>

            <div class="single-work-page__image single-work-page__image--w-full single-work-adaptive__image ">
                <img src="https://m2perspective.test/media/wysiwyg/works/vodafone/vod-adaptive.png" alt="Vodafone online store adaptive screen" />
            </div>
        </section>
        <section class="single-work-page__testimonials single-work-testimonials">
            <div class="single-work-testimonials__body _grid-2-col">
                <div class="single-work-testimonials__label _section-label">Testimonials</div>

                <div class="single-work-testimonials__content">
                    <h3 class="single-work-testimonials__title single-work-section__title">What our client say about us</h3>
                    <script type="text/javascript" src="https://widget.clutch.co/static/js/widget.js" async></script> <div class="clutch-widget" data-url="https://widget.clutch.co" data-widget-type="4" data-height="auto" data-nofollow="true" data-expandifr="true" data-scale="100" data-scale="100" data-reviews="" data-clutchcompany-id="1306745"></div>
                </div>

            </div>
        </section>

    </div>
</div>
