<div class="careers-page">
    <div class="careers-page__intro ">
        <div class="careers-page__container _container _grid-3-col">
            <h2 class="careers-page__title _page-title ">
                <p>Want to be part</p>
                <p>
                    of our <span class="_page-title--orange">magento</span> team?
                </p>
            </h2>
            <h4 class="careers-page__sub-title _page-sub-title">The most important thing is the atmosphere in the team. For us, this is a state of constant development and growth, as well as family values, where everyone is friendly, caring and easy to communicate with.</h4>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--team ">
        <div class="careers-section__container _container  _grid-3-col">


            <div class="careers-section__section-label _section-label">Meet Our Team</div>

            <div class="careers-section__col">
                <h3 class="careers-section__title">who we are</h3>
                <h5 class="careers-section__text">Perspective is a Ukrainian, Magento-oriented team, with a bias towards the technical component of projects. We are represented in 4 cities: Kiev, Uzhgorod, Krivoy Rog and Shostka. </h5>
                <h5 class="careers-section__text">Our clients are 70% Western companies (Europe and the USA) and 30% Ukrainian companies. Our goal is to be the best Magento experts.</h5>
            </div>

            <div class="careers-section__col">
                <div class="careers-section__squares careers-squares">
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">12</div>
                        <p class="careers-squares__text">front-end <br /> developers</p>
                    </div>
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">32</div>
                        <p class="careers-squares__text">back-end <br /> developers</p>
                    </div>
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">4</div>
                        <p class="careers-squares__text">DevOps <br /> & SysOps</p>
                    </div>
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">6</div>
                        <p class="careers-squares__text">qa - 6 employees <br /> & team lead</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--benefits ">
        <div class="careers-section__container _container  _grid-3-col">
            <div class="careers-section__section-label _section-label">Benefits</div>
            <div class="careers-section__cell">
                <h3 class="careers-section__title">What we offer</h3>
                <h5 class="careers-section__text">The most important thing is the atmosphere in the team. For us, this is a state of constant development and growth, as well as family values, where everyone is friendly, caring and easy to communicate with.</h5>

                <div class="_h4">Magento expertise</div>
                <ul class="careers-section__list _list">
                    <li>We hold internal and external Magento meetups, upgrade our speakers and invite external experts.</li>
                    <li>We drive the spirit of constant development - weekly Magento meetings and full preparation of each employee for certification.</li>
                </ul>
            </div>
            <div class="careers-section__cell">
                <div class="careers-section__image">
                    <img src="{{media url='wysiwyg/careers/3Z_2009.w020.n001.635B.p15.635_Converted_1.png'}}" alt="">
                </div>
            </div>

            <div class="careers-section__empty-cell"></div>
            <div class="careers-section__cell">
                <div class="_h4">Professional and personal growth</div>
                <ul class="careers-section__list _list">
                    <li>We provide vertical growth. </li>
                    <li>The staff has a teacher in Magento development and in English.</li>
                    <li>Sometimes, to expand the team, we conduct public Magento courses at the university.</li>
                    <li>You can count on partial or full compensation for training - courses, conferences, meetups, etc.</li>
                    <li>You will have access to an internal offline and online library, which contains professional literature for all specialists.</li>
                </ul>

                <div class="careers-section__image">
                    <img src="{{media url='wysiwyg/careers/2109.w032.n003.103B.p1.103_Converted_1.png'}}" alt="">              
                </div>
            </div>
            <div class="careers-section__cell">
                <div class="_h4">Work & Life balance</div>
                <p>Despite the fact that our clients are distributed all over the world, we have a standardized schedule. We do our best to avoid overtime. But even if they happen, your time will be paid by the coefficient.</p>
                <div class="_h4">salary</div>
                <ul class="careers-section__list _list">
                    <li>Regular reviews, at least twice a year, as well as after Magento certification</li>
                    <li>Referral program - bonus for recommending a future colleague</li>
                    <li>Partial tax refund</li>
                    <li>24 working days of vacation</li>
                    <li>20 working days sick leave</li>
                </ul>

                <div class="_h4">Gamification</div>
                <p>Gamification - by performing certain actions, earn internal currency and exchange it for corporate merchandise or other goodies from the company</p>

            </div>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--join-us">
        <div class="careers-section__container _container  _grid-2-col">
            <div class="careers-section__section-label _section-label">Join us!</div>
            <div class="careers-section__content">
                <h3 class="careers-section__title">We are <br /> looking for</h3>

                <div class="careers-section__collapsible careers-collapsible" data-mage-init='{"accordion":{
                        "animate":{ "duration" :400, "easing":"easeOutCubic"},
                        "active": [],
                        "collapsible": true,
                        "openedState": "active",
                        "multipleCollapsible": true}}'>
                    <div data-role="collapsible" class="careers-collapsible__item">
                        <div data-role="trigger" class="careers-collapsible__trigger">
                            <div class="careers-collapsible__header">
                                <h5 class="careers-collapsible__title">Back-End Developer </h5>
                                <p class="careers-collapsible__locate">Cherkasy, Kryvyi Rih</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>
                        </div>

                    </div>
                    <div data-role="content">
                        <p>text</p>
                    </div>

                    <div data-role="collapsible" class="careers-collapsible__item">
                        <div data-role="trigger" class="careers-collapsible__trigger">
                            <div class="careers-collapsible__header">
                                <h5 class="careers-collapsible__title">Magento Back-end Developer</h5>
                                <p class="careers-collapsible__locate">Cherkasy, Uzhhorod, Kryvyi Rih, Shostka</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>

                        </div>
                    </div>
                    <div data-role="content">
                        <p>text</p>
                    </div>

                    <div data-role="collapsible" class="careers-collapsible__item">
                        <div data-role="trigger" class="careers-collapsible__trigger">
                            <div class="careers-collapsible__header">
                                <h5 class="careers-collapsible__title">Project Manager</h5>
                                <p class="careers-collapsible__locate">Kyiv</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>

                        </div>
                    </div>
                    <div data-role="content">
                        <p>text</p>
                    </div>

                    <div data-role="collapsible" class="careers-collapsible__item">
                        <div data-role="trigger" class="careers-collapsible__trigger">
                            <div class="careers-collapsible__header">
                                <h5 class="careers-collapsible__title">Sales Development Representative</h5>
                                <p class="careers-collapsible__locate">Kyiv</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>

                        </div>
                    </div>
                    <div data-role="content">
                        <p>text</p>
                    </div>

                    <div data-role="collapsible" class="careers-collapsible__item">
                        <div data-role="trigger" class="careers-collapsible__trigger">
                            <div class="careers-collapsible__header">
                                <h5 class="careers-collapsible__title">QA engineer</h5>
                                <p class="careers-collapsible__locate">Uzhhorod, Shostka</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>

                        </div>
                    </div>
                    <div data-role="content">
                        <div class="careers-collapsible__content">
                            <div class="careers-collapsible__col">
                                <h5 class="careers-collapsible__text">Our team specializes in an integrated approach to web development and graphics services. The key area of ​​e-commerce. We are also growing in search of a new motivated and purposeful QA that will join our best Magento Team.</h5>
                                <button class="careers-collapsible__button careers-collapsible__button--desktop _button _button--orange-bg">Send your CV</button>
                            </div>

                            <div class="careers-collapsible__col">
                                <h5 class="careers-collapsible__list-legend">Responsibilities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>manual testing of ready-made websites</li>
                                    <li>development, updating of test documentation and work with it</li>
                                    <li>create and execute test scenarios</li>
                                    <li>support and creation of technical documentation</li>
                                    <li>communication with developers and QA at all stages of testing</li>
                                    <li>to plan and give estimates of terms of works on carrying out testing</li>
                                </ul>

                                <h5 class="careers-collapsible__list-legend">Requirements to the applicant:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>understanding of the software development and quality control cycle</li>
                                    <li>experience with JIRA: - white, gray, black - box, regression, penetration - testing</li>
                                    <li>TK testing</li>
                                    <li>be able to quickly switch between tasks and efficiently distribute their time between them</li>
                                    <li>knowledge of the principles of Scrum, Agile</li>
                                    <li>knowledge of HTML, CSS, JavaScript.</li>
                                </ul>

                                <h5 class="careers-collapsible__list-legend">Will be a plus:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>knowledge of Protractor, Selenium frameworks</li>
                                    <li>automation of testing processes</li>
                                    <li>experience with git, Apache JMeter.</li>
                                </ul>
                            </div>

                            <button class="careers-collapsible__button careers-collapsible__button--mobile _button _button--orange-bg">Send your CV</button>

                        </div>
                    </div>


                    <div data-role="collapsible" class="careers-collapsible__item">
                        <div data-role="trigger" class="careers-collapsible__trigger">
                            <div class="careers-collapsible__header">
                                <h5 class="careers-collapsible__title">People Manager, OM</h5>
                                <p class="careers-collapsible__locate">Kyiv</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>

                        </div>
                    </div>

                    <div data-role="content">
                        <p>text</p>
                    </div>

                    <div data-role="collapsible" class="careers-collapsible__item">
                        <div data-role="trigger" class="careers-collapsible__trigger">
                            <div class="careers-collapsible__header">
                                <h5 class="careers-collapsible__title">DevOps engineer</h5>
                                <p class="careers-collapsible__locate">Cherkasy, Uzhhorod, Shostka</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>

                        </div>
                    </div>
                    <div data-role="content">
                        <p>text</p>
                    </div>

                    <div data-role="collapsible" class="careers-collapsible__item">
                        <div data-role="trigger" class="careers-collapsible__trigger">
                            <div class="careers-collapsible__header">
                                <h5 class="careers-collapsible__title">QA engineer</h5>
                                <p class="careers-collapsible__locate">Uzhhorod, Shostka</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>

                        </div>
                    </div>
                    <div data-role="content">
                        <p>text</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>