<div class="company-page" data-mage-init='{"slickCompanyPage" : {}, "companyPage" : {} }'>
    <div class="company-page__container _container">
        <div class="company-page__top">
            <h1 class="h2 company-page__title">
                We are a team of international experts united by a <span class="company-page__title--orange">single goal</span>
            </h1>
            <h2 class="h4 company-page__sub-title _text-align-right">We help make money on the Internet and contribute to business development by introducing IT innovations into them.</h2>
            <div class="company-page__image">
                <img loading="eager" src="{{media url='wysiwyg/company/background-about.png'}}" alt="sec">
            </div>
            <div class="company-page__squares company-squares">
                <div class="company-squares__text _text-align-right">
                    <h5 class="h5">We are the Magento-focused web-development company named Perspective Studio, with HQ in Kyiv, Ukraine, with more than 60 employees. </h5>
                </div>
                <div class="company-squares__square company-square company-square--fronts">
                    <div class="company-square__digit">10</div>
                    <p class="company-square__text">front-end <br /> developers</p>
                </div>
                <div class="company-squares__square company-square company-square--backs">
                    <div class="company-square__digit">32</div>
                    <p class="company-square__text">back-end <br /> developers</p>
                </div>
                <div class="company-squares__square company-square company-square--qa">
                    <div class="company-square__digit">12</div>
                    <p class="company-square__text">QA engineers <br />& team lead</p>
                </div>
                <div class="company-squares__square company-square company-square--devops">
                    <div class="company-square__digit">4</div>
                    <p class="company-square__text">DevOps <br />& SysOps</p>
                </div>
            </div>
        </div>

        <section class="company-page__growth company-growth">
            <div class="company-growth__body _grid-2-col">
                <div class="company-growth__label _section-label">Growth</div>
                <div class="company-growth__content">
                    <div class="company-growth__top">
                        <h5 class="h5 company-growth__text">Our company was founded in 2009 and initially dealt with different CMS and Frameworks. Still, after some time, we realized that we should have a definite aim to develop ourselves in one thing, mastering skills in a narrow area.</h5>
                        <h5 class="h5 company-growth__text _text-align-right">Perspective Studio has seen constant annual growth and success since its inception. We currently have five offices in Kyiv, Uzhhorod, Shostka, Cherkasy, and Kryvyi Rih.
                        </h5>
                    </div>

                    <div class="company-growth__bottom">
                        <h3 class="h3 company-growth__title">Our aim is to become <span class="company-growth__title--orange">the Best</span> Magento Team ever</h3>
                        <div class="company-growth__image company-map-image" data-mage-init='{"companyImageAnimation" : {}}'>
                            <div class="company-map-image__container">
                                <div class="highlight" style="width:100%">
                                    <img loading="lazy" src="{{media url='wysiwyg/company/map/highlight.svg'}}" alt="hover" />
                                </div>
                                <div class="ukraine" style="width:100%">
                                    <img loading="lazy" src="{{media url='wysiwyg/company/map/ukraine.svg'}}" alt="hover" />
                                </div>
                                <div class="uzh">
                                    <img loading="lazy" src="{{media url='wysiwyg/company/map/uzh.svg'}}" alt="hover" />
                                </div>
                                <div class="shost">
                                    <img loading="lazy" src="{{media url='wysiwyg/company/map/shost.svg'}}" alt="hover" />
                                </div>
                                <div class="kyiv">
                                    <img loading="lazy" src="{{media url='wysiwyg/company/map/kyiv.svg'}}" alt="hover" />
                                </div>
                                <div class="kr">
                                    <img loading="lazy" src="{{media url='wysiwyg/company/map/kr.svg'}}" alt="hover" />
                                </div>
                                <div class="cher">
                                    <img loading="lazy" src="{{media url='wysiwyg/company/map/cher.svg'}}" alt="hover" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="company-page__team company-team">
            <div class="company-team__body _grid-2-col">
                <div class="company-team__label _section-label">Meet Our Team</div>
                <div class="company-team__content">
                    <h3 class="h3 company-team__title">Key persons of the company</h3>
                    <h5 class="h5 company-team__sub-title _text-align-right">Perspective is the experts in their respective fields and a truly stellar team of executives that work hard every day to ensure that our Сompany offers the best services in the e-commerce industry. Team growth and implementation of best practices are what the guys do every day.
                    </h5>
                    <div class="company-team__gallery team-gallery">
                        <div class="team-gallery__col">
                            <div class="team-gallery__person" data-container-pos="1">
                                <div data-pos-desktop="1" data-pos-mobile="2">
                                    <div class="team-gallery__photo">
                                        <img loading="eager" src="{{media url='wysiwyg/company/Mik.png'}}" alt="Mikhail">
                                    </div>
                                    <div class="team-gallery__label team-gallery__label--mik photo-label">
                                        <div class="photo-label__name">Mikhail Knyr</div>
                                        <div class="photo-label__position">Partner</div>
                                    </div>
                                </div>
                            </div>

                            <div class="team-gallery__person" data-container-pos="2">
                                <div data-pos-desktop="2" data-pos-mobile="4">
                                    <div class="team-gallery__photo">
                                        <img loading="eager" src="{{media url='wysiwyg/company/Al.png'}}" alt="Alyona">
                                    </div>
                                    <div class="team-gallery__label team-gallery__label--ale photo-label">
                                        <div class="photo-label__name">Alena Karasevich</div>
                                        <div class="photo-label__position">HR Lead</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="team-gallery__col">
                            <div class="team-gallery__person">
                                <div class="team-gallery__photo">
                                    <img loading="eager" src="{{media url='wysiwyg/company/Yar.png'}}" alt="Yaroslav">
                                </div>
                                <div class="team-gallery__label team-gallery__label--yar photo-label">
                                    <div class="photo-label__name">Yaroslav Zinchuk</div>
                                    <div class="photo-label__position">PM Lead</div>
                                </div>
                            </div>

                            <div class="team-gallery__person" data-container-pos="4">
                                <div data-pos-desktop="4" data-pos-mobile="5">
                                    <div class="team-gallery__photo">
                                        <img loading="eager" src="{{media url='wysiwyg/company/Nat.png'}}" alt="Natalya">
                                    </div>
                                    <div class="team-gallery__label team-gallery__label--nata photo-label">
                                        <div class="photo-label__name">Natalya Stupakova</div>
                                        <div class="photo-label__position">FN Lead</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="team-gallery__col">
                            <div class="team-gallery__person team-gallery__person--art" data-container-pos="5">
                                <div data-pos-desktop="5" data-pos-mobile="1">
                                    <div class="team-gallery__photo">
                                        <img loading="eager" src="{{media url='wysiwyg/company/Art.png'}}" alt="Artur">
                                    </div>
                                    <div class="team-gallery__label team-gallery__label--art photo-label">
                                        <div class="photo-label__name">Artur Potulny</div>
                                        <div class="photo-label__position">CEO</div>
                                    </div>
                                </div>
                            </div>

                            <div class="team-gallery__person ">
                                <div class="team-gallery__photo">
                                    <img loading="eager" src="{{media url='wysiwyg/company/Arn.png'}}" alt="Arnold">
                                </div>
                                <div class="team-gallery__label team-gallery__label--arn photo-label">
                                    <div class="photo-label__name">Viktor Klimovych</div>
                                    <div class="photo-label__position">Business Developer</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section class="company-page__gallery company-gallery">
            <div class="company-gallery__body _grid-2-col">
                <h3 class="h3 company-gallery__title">
                    We are like <span class="company-gallery__title--orange">a family</span> with common goals, <span class="company-gallery__title--orange">a team</span> of like-minded people driven by <span class="company-gallery__title--orange">passion to what we do</span>
                </h3>
                <div class="company-gallery__image company-gallery__image--panorama">
                    <img loading="lazy" src="{{media url='wysiwyg/company/total_1.png'}}" alt="background-gallery">
                </div>
                <div class="company-gallery__photos gallery-photos">
                    <div class="gallery-photos__col">
                        <div class="gallery-photos__item">
                            <img loading="lazy" src="{{media url='wysiwyg/company/2.png'  }}" alt="sec">
                        </div>
                        <div class="gallery-photos__item">
                            <img loading="lazy" src="{{media url='wysiwyg/company/1.png'}}" alt="frst">
                        </div>

                        <a href="#footer-alt" class="gallery-photos__button _button _button--orange-bg _button--arrow _scrollTo">
                            <h5 class="h5 _button__text">Join the team</h5>
                            <span class="_button__overlay _button__overlay--hover"></span>
                            <span class="_button__overlay _button__overlay--active"></span>
                        </a>
                    </div>
                    <div class="gallery-photos__col ">
                        <h5 class="h5 gallery-photos__sub-title _text-align-right">Sure, we know how to work together, but we also know how to play together. A friendly atmosphere helps build strong relationships, unique projects, and an environment that puts people first—and they know it.</h5>
                        <div class="gallery-photos__item">
                            <img loading="lazy" src="{{media url='wysiwyg/company/4.png' }}" alt="four">
                        </div>

                        <div class="gallery-photos__item">
                            <img loading="lazy" src="{{media url='wysiwyg/company/3.png'}}" alt="three">
                        </div>
                    </div>

                    <div class="gallery-photos__col gallery-photos__col--mobile">

                    </div>
                </div>
            </div>
        </section>

        <section class="company-page__pets company-pets">
            <div class="company-pets__body _grid-2-col">
                <div class="company-pets__label _section-label">Pet-friendly</div>
                <div class="company-pets__content">
                    <h3 class="h3 company-pets__title">Man’s Best Friends at Work</h3>
                    <h5 class="h5 company-pets__sub-title _text-align-right">We realize how beneficial and essential a pet-friendly office is for our employees. Pets in the workplace have a way of bringing people together, which is critical for being both interactive and productive.</h5>
                    <div class="company-pets__gallery pets-gallery">
                        <div class="pets-gallery__col">
                            <div class="pets-gallery__image">
                                <img loading="lazy" src="{{media url='wysiwyg/company/1_1.png'}}" alt="fst">
                            </div>
                            <div class="pets-gallery__image">
                                <img loading="lazy" src="{{media url='wysiwyg/company/3_1.png'}}" alt="three">
                            </div>
                        </div>

                        <div class="pets-gallery__col">
                            <div class="pets-gallery__image">
                                <img loading="lazy" src="{{media url='wysiwyg/company/4_1.png'}}" alt="four">
                            </div>
                            <div class="pets-gallery__image">
                                <img loading="lazy" src="{{media url='wysiwyg/company/2_1.png'}}" alt="sec">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>