<div class="container main-page">
    <!-- BG image (SVG) add to page using CSS pseudo-element :after-->
    <div class="main-page__bg-image"></div>

    <div class="main-intro">
        <div class="main-intro__body _container">
            <div class="main-intro__title intro-title">
                <div class="intro-title__top">
                    <div class="intro-title__left _sliding-text">
                        <p class="intro-title__big-letters _sliding-text__line">
                            We are&nbsp;
                        </p>
                        <p class="intro-title__big-letters _sliding-text__line">
                            your best
                        </p>
                    </div>
                    <div class="intro-title__right">
                        <p class="intro-title__sub-title">
                            web design <br />project development
                            <br />integration with external systems
                            <br />support and scale
                        </p>
                    </div>
                </div>
                <div class="intro-title__bottom _sliding-text">
                    <span class="intro-title__big-letters _sliding-text__line">
                        <span
                            class="intro-title__big-letters intro-title__big-letters--orange"
                            >magento</span
                        >
                        Team
                    </span>
                </div>
            </div>
            <div class="main-intro__digits digits-intro">
                <div class="digits-intro__item">
                    <div class="digits-intro__number">12</div>
                    <div class="digits-intro__text">
                        years <br />of experience
                    </div>
                </div>
                <div class="digits-intro__item">
                    <div class="digits-intro__number">67</div>
                    <div class="digits-intro__text">
                        employees <br />in the team
                    </div>
                </div>
                <div class="digits-intro__item">
                    <div class="digits-intro__number">42</div>
                    <div class="digits-intro__text">
                        successfull <br />projects
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="orange-block">
        <div class="orange-block__container _container _grid-2-col">
            <div class="orange-block__col">
                <div class="_section-label _section-label--white">
                    How we do it
                </div>
            </div>
            <div class="orange-block__col">
                <h3 class="orange-block__title _sliding-text">
                    <span class="_sliding-text__line">Your roadmap</span>
                    <br /><span class="_sliding-text__line">to success</span>
                </h3>
                <div class="vector-absolute-images">
                    <div class="images-card-element">
                        <img
                            class="Rocet-1 rocket"
                            src="{{media url='wysiwyg/Main/Rocet.png'}}"
                            alt="line"
                        /><img
                            class="lineV-1 line"
                            src="{{media url='wysiwyg/Main/LineV.png'}}"
                            alt="line"
                        />
                        <div class="success__describe--item">
                            <span class="text">01. Research </span
                            ><span class="text">&amp; analysis</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img
                            class="Rocet-2 rocket"
                            src="{{media url='wysiwyg/Main/Rocet.png'}}"
                            alt="line"
                        /><img
                            class="lineV-2 line"
                            src="{{media url='wysiwyg/Main/LineV.png'}}"
                            alt="line"
                        />
                        <div class="success__describe--item">
                            <span class="text">02. Planning </span
                            ><span class="text">&amp; estimation</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img
                            class="Rocet-3 rocket"
                            src="{{media url='wysiwyg/Main/Rocet.png'}}"
                            alt="line"
                        /><img
                            class="lineV-3 line"
                            src="{{media url='wysiwyg/Main/LineV.png'}}"
                            alt="line"
                        />
                        <div class="success__describe--item">
                            <span class="text">03. Designing </span
                            ><span class="text">user interfaces</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img
                            class="Rocet-4 rocket"
                            src="{{media url='wysiwyg/Main/Rocet.png'}}"
                            alt="line"
                        /><img
                            class="lineV-4 line"
                            src="{{media url='wysiwyg/Main/LineV.png'}}"
                            alt="line"
                        />
                        <div class="success__describe--item">
                            <span class="text">04. Development </span
                            ><span class="text">&amp; Coding</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img
                            class="Rocet-5 rocket"
                            src="{{media url='wysiwyg/Main/Rocet.png'}}"
                            alt="line"
                        /><img
                            class="lineV-5 line"
                            src="{{media url='wysiwyg/Main/LineV.png'}}"
                            alt="line"
                        />
                        <div class="success__describe--item">
                            <span class="text">05. Validate </span
                            ><span class="text">&amp; beta test</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img
                            class="Rocet-6 rocket"
                            src="{{media url='wysiwyg/Main/Rocet.png'}}"
                            alt="line"
                        /><img
                            class="lineV-6 line"
                            src="{{media url='wysiwyg/Main/LineV.png'}}"
                            alt="line"
                        />
                        <div class="success__describe--item">
                            <span class="text">06. Deployment </span
                            ><span class="text">&amp; Maintenance</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="digital-block _container">
        <div class="digital-block__body _grid-2-col">
            <div class="digital-block__section-label">
                <div class="_section-label">Services</div>
            </div>

            <div class="digital-block__content">
                <div class="digital-block__top">
                    <div class="digital-block__describe">
                        <h3 class="digital-block__title _sliding-text">
                            <span class="_sliding-text__line">All Digital Services</span>
                            <br />
                            <span class="_sliding-text__line">Under One Roof</span>
                        </h3>
                        <h5 class="digital-block__sub-title _text-align-right">
                            We have a wealth of experience working with
                            corporate and personal clients. Many of those
                            clients have been working with us for more than 5
                            years.
                        </h5>
                    </div>
                    <div class="digital-block__image">
                        <img
                            class="img-fst"
                            src="{{media url='wysiwyg/Main/Cube.png'}}"
                            alt="Cube-service "
                        />
                    </div>
                </div>

                <div class="digital-block__bot">
                    <div
                        class="digital-block__squares digital-squares digital-squares--desk"
                    >
                        <div class="digital-squares__row">
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Web Design</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento Development</h4>
                                </div>
                            </div>
                            <div class="digital-squares__empty"></div>
                            <div class="digital-squares__empty"></div>
                        </div>

                        <div class="digital-squares__row">
                            <div class="digital-squares__empty"></div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento 2 Migration</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento PWA</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento Support</h4>
                                </div>
                            </div>
                        </div>

                        <div class="digital-squares__row">
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Server & Magento Optimization</h4>
                                </div>
                            </div>
                            <div class="digital-squares__empty"></div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento Security Audit</h4>
                                </div>
                            </div>
                            <div
                                class="digital-squares__item digital-squares__item--no-border--centered"
                            >
                                <a href="#" class="digital-block__link"
                                    >Discover more</a
                                >
                            </div>
                        </div>
                    </div>

                    <div
                        class="digital-block__squares digital-squares digital-squares--mob"
                    >
                        <div class="digital-squares__col">
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento Development</h4>
                                </div>
                            </div>

                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento PWA</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Server & Magento Optimization</h4>
                                </div>
                            </div>
                        </div>
                        <div class="digital-squares__col">
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Web Design</h4>
                                </div>
                            </div>

                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento 2 Migration</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento Support</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4>Magento Security Audit</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="digital-block__show-more">
                    <a
                        class="digital-block__link _link-arrow"
                        href="{{store url='services'}}"
                    >
                        Discover more
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="integration _container">
        <div class="integration__body _grid-2-col">
            <div class="integration__section-label">
                <div class="_section-label">Integration</div>
            </div>
            <div class="integration__body">
                <div class="integration__top">
                    <div class="integration__image">
                        <img
                            class="describe__image--item"
                            src="{{media url='wysiwyg/Main/integration.png'}}"
                            alt="integration "
                        />
                        <h5
                            class="integration__text integration__text--mobile _text-align-right"
                        >
                            Integrate your Magento website with any backend
                            system or external software to automate your work
                            processes and execute your business strategy more
                            efficiently.
                        </h5>
                    </div>
                    <div class="integration__content">
                        <h3 class="integration__title _sliding-text">
                          <span class="_sliding-text__line">Integrate with </span>
                          <br /><span class="_sliding-text__line">any ecommerce</span>
                          <br /><span class="_sliding-text__line">services</span>
                        </h3>
                        <h5 class="integration__text _text-align-right">
                          Integrate your Magento website with any backend system or external
                          software to automate your work processes and execute your business
                          strategy more efficiently.
                        </h5>
                    </div>
                </div>
                <div class="integration__bot">
                    <div class="integration__cards integration-cards">
                        <div class="integration-cards__item">
                            <h4 class="integration-cards__title">
                                Headless CMS
                            </h4>
                            <input
                                type="checkbox"
                                id="integration-cards__arrow_1"
                                class="integration-cards__arrow"
                            />
                            <label for="integration-cards__arrow_1"></label>
                            <div class="integration-cards__image">
                                <img
                                    class="image-integration"
                                    src="{{media url='wysiwyg/Main/left_1.png'}}"
                                    alt="hover"
                                />
                            </div>
                        </div>

                        <div class="integration-cards__item">
                            <h4 class="integration-cards__title">Payments</h4>
                            <input
                                type="checkbox"
                                id="integration-cards__arrow_2"
                                class="integration-cards__arrow"
                            />
                            <label for="integration-cards__arrow_2"></label>
                            <div class="integration-cards__image">
                                <img
                                    class="image-integration"
                                    src="{{media url='wysiwyg/Main/payment.png'}}"
                                    alt="hover"
                                />
                            </div>
                        </div>

                        <div class="integration-cards__item">
                            <h4 class="integration-cards__title">
                                Any third-party service
                            </h4>

                            <input
                                type="checkbox"
                                id="integration-cards__arrow_3"
                                class="integration-cards__arrow"
                            />
                            <label for="integration-cards__arrow_3"></label>

                            <div class="integration-cards__image">
                                <img
                                    class="image-integration"
                                    src="{{media url='wysiwyg/Main/left_1.png'}}"
                                    alt="hover"
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="company">
        <div class="company__container _container">
            <div class="company__body _grid-3-col">
                <div class="company__section-label _section-label">Company</div>
                <div class="company__col">
                    <h3 class="company__title _sliding-text">
                        <span class="_sliding-text__line">Who we are</span>
                    </h3>
                    <h5 class="company__text _text-align-right">
                        With more than a decade of experience, Perspective has
                        become a leader in digital experiences. Clients
                        worldwide entrust us with the design, development and
                        management of their websites.
                    </h5>

                    <div
                        class="company__squares squares-company squares-company--mobile"
                    >
                        <div class="squares-company__square">
                            <div class="squares-company__number">12</div>
                            <h5 class="squares-company__text">
                                front-end developers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">32</div>
                            <h5 class="squares-company__text">
                                back-end developers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">6</div>
                            <h5 class="squares-company__text">
                                qa - 6 employees & team lead
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">4</div>
                            <h5 class="squares-company__text">
                                DevOps & SysOps
                            </h5>
                        </div>
                    </div>
                    <h5 class="company__text _text-align-right">
                        We are the Magento focused web-development company named
                        Perspective Studio with HQ located in Kyiv, Ukraine with
                        more than 67 employees. Most of them are strong middle
                        and senior developers with 5+ years of experience in
                        Magento.
                    </h5>
                    <div class="company__image">
                        <img
                            src="{{media url='wysiwyg/Main/who-we.png'}}"
                            alt="who-we-are"
                        />
                    </div>
                </div>
                <div class="company__col">
                    <div
                        class="company__squares squares-company squares-company--desktop"
                    >
                        <div class="squares-company__square">
                            <div class="squares-company__number">12</div>
                            <h5 class="squares-company__text">
                                front-end developers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">32</div>
                            <h5 class="squares-company__text">
                                back-end developers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">6</div>
                            <h5 class="squares-company__text">
                                qa - 6 employees & team lead
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">4</div>
                            <h5 class="squares-company__text">
                                DevOps & SysOps
                            </h5>
                        </div>
                    </div>
                    <h5 class="company__text _text-align-right">
                        Our philosophy is built on people who love creating,
                        learning and growing together. Our studio of more than
                        60 people who form a team with ties that transcend the
                        workplace.
                    </h5>

                    <div class="company__button-box">
                        <a href="{{store url='company'}}">
                            <button
                                class="company__button _button _button--white"
                            >
                                <span> More about us</span>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="work">
        <div class="work__container _container">
            <div class="work__body _grid-2-col">
                <div class="work__section-label _section-label">Work</div>
                <div class="work__content">
                    <h3 class="work__title _sliding-text">
                        <span class="_sliding-text__line">We build timeless</span>
                        <br /><span class="_sliding-text__line">experiences</span>
                    </h3>
                    <div class="work__gallery gallery">
                        <div class="gallery__container">
                            <div class="gallery__content">
                                <div class="gallery__col">
                                    <div
                                        class="gallery__text _text-align-right"
                                    >
                                        We develop, design and delivers websites
                                        that drive results. Our work never
                                        brags, but it sure loves to speak for
                                        itself.
                                    </div>
                                    <div class="gallery__slide gallery-slide">
                                        <div class="gallery-slide__image">
                                            <img
                                                src="{{media url='wysiwyg/Main/tefal.png'}}"
                                                alt="tefal"
                                            />
                                        </div>
                                        <div class="gallery-slide__content">
                                            <span class="gallery-slide__title">
                                                Tefal
                                            </span>
                                            <p class="gallery-slide__text">
                                                Design, development,
                                                integrations,support
                                            </p>
                                        </div>
                                    </div>
                                    <div class="gallery__slide gallery-slide">
                                        <div class="gallery-slide__image">
                                            <img
                                                src="{{media url='wysiwyg/Main/berg.png'}}"
                                                alt="berg "
                                            />
                                        </div>
                                        <div class="gallery-slide__content">
                                            <span class="gallery-slide__title">
                                                Dr.Berg
                                            </span>
                                            <p class="gallery-slide__text">
                                                Development, integrations,
                                                support
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="gallery__col gallery__col--reverse">
                                    <div class="gallery__show-more">
                                        <p>See all work</p>
                                        <div class="icon-arrow">&nbsp;</div>
                                    </div>
                                    <div class="gallery__slide gallery-slide">
                                        <div class="gallery-slide__image">
                                            <img
                                                src="{{media url='wysiwyg/Main/ortlieb.png'}}"
                                                alt="ortrieb "
                                            />
                                        </div>
                                        <div class="gallery-slide__content">
                                            <span class="gallery-slide__title">
                                                Ortrieb
                                            </span>
                                            <p class="gallery-slide__text">
                                                Development, integrations,
                                                support
                                            </p>
                                        </div>
                                    </div>
                                    <div class="gallery__slide gallery-slide">
                                        <div class="gallery-slide__image">
                                            <img
                                                src="{{media url='wysiwyg/Main/vodofon.png'}}"
                                                alt="vodofon "
                                            />
                                        </div>
                                        <div class="gallery-slide__content">
                                            <span class="gallery-slide__title">
                                                Vodafon
                                            </span>
                                            <p class="gallery-slide__text">
                                                Development, integrations,
                                                support
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="gallery__col--mobile"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="trusted">
        <div class="trusted__container _container">
            <div class="trusted__body _grid-2-col">
                <div class="trusted__section-label _section-label">
                    Our clients
                </div>
                <div class="trusted__content">
                    <div class="trusted__header">
                        <h3 class="trusted__title _sliding-text">
                          <span class="_sliding-text__line">We are trusted</span>
                        </h3>
                        <h5 class="trusted__sub-title _text-align-right">
                          We make Magento work for our clients with perfect codes, engaging
                          interactions, thoughtful integrations and a commitment to ongoing
                          support.
                        </h5>
                    </div>

                    <div class="trusted__table trusted-table">
                        <div
                            class="trusted-table__item trusted-table__item--empty"
                        ></div>
                        <div
                            class="trusted-table__item trusted-table__item--empty"
                        ></div>
                        <div
                            class="trusted-table__item trusted-table__item--empty"
                        ></div>
                        <div
                            class="trusted-table__item trusted-table__item--krups"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/krups.png'}}"
                                    alt="krups"
                                />
                            </div>
                        </div>

                        <div
                            class="trusted-table__item trusted-table__item--vod"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/Vodafone.png'}}"
                                    alt="vodofon "
                                />
                            </div>
                        </div>
                        <div
                            class="trusted-table__item trusted-table__item--tef"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/tefal.png'}}"
                                    alt="tefal "
                                />
                            </div>
                        </div>
                        <div
                            class="trusted-table__item trusted-table__item--tmm"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/tmm.png'}}"
                                    alt="tmm "
                                />
                            </div>
                        </div>
                        <div
                            class="trusted-table__item trusted-table__item--chic"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/chicco.png'}}"
                                    alt="chicco "
                                />
                            </div>
                        </div>

                        <div
                            class="trusted-table__item trusted-table__item--dr"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/DrBerg.png'}}"
                                    alt="berg "
                                />
                            </div>
                        </div>
                        <div
                            class="trusted-table__item trusted-table__item--2-col trusted-table__item--aphid"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/AphidDigital.png'}}"
                                    alt="degital "
                                />
                            </div>
                        </div>
                        <div
                            class="trusted-table__item trusted-table__item--ortl"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/Ortlieb_.png'}}"
                                    alt="ortlieb "
                                />
                            </div>
                        </div>

                        <div
                            class="trusted-table__item trusted-table__item--empty"
                        ></div>
                        <div
                            class="trusted-table__item trusted-table__item--sea"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/Seaguar.png'}}"
                                    alt="seguar "
                                />
                            </div>
                        </div>
                        <div
                            class="trusted-table__item trusted-table__item--good"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/Goodvine.png'}}"
                                    alt="goodvine "
                                />
                            </div>
                        </div>
                        <div
                            class="trusted-table__item trusted-table__item--empty"
                        ></div>

                        <div
                            class="trusted-table__item trusted-table__item--dfg"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/Degrau.png'}}"
                                    alt="degrau "
                                />
                            </div>
                        </div>
                        <div
                            class="trusted-table__item trusted-table__item--hum"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/HUMco.png'}}"
                                    alt="HUMco "
                                />
                            </div>
                        </div>
                        <div
                            class="trusted-table__item trusted-table__item--2-col trusted-table__item--beach"
                        >
                            <div class="trusted-table__image">
                                <img
                                    src="{{media url='wysiwyg/Main/logo/Beachcomer.png'}}"
                                    alt="beach "
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="comments">
        <div class="comments__container _container _grid-2-col">
            <div class="comments__section-label _section-label">
                Testimonials
            </div>
            <div class="comments__body">
                <div class="comments__header">
                    <h3 class="comments__title _sliding-text">
                      <span class="_sliding-text__line">What our clients</span>
                      <br /><span class="_sliding-text__line">say about us</span>
                    </h3>
                    <h5 class="comments__sub-title _text-align-right">
                      We have a wealth of experience working with corporate and personal
                      clients. Many of those clients have been working with us for more
                      than 5 years
                    </h5>
                </div>

                <div class="comments__content">
                    <ul class="comments__list">
                        <div class="comments__item comment">
                            <div class="comment__header">
                                <div class="comment__icon">
                                    <img
                                        src="{{media url='wysiwyg/Main/message/Group.png'}}"
                                        alt="C "
                                    />
                                </div>
                                <div class="comment__rate">
                                    <div class="comment__rate-number">
                                        <span>5.0</span>
                                    </div>
                                    <div class="comment__stars">
                                        <span class="stars-icons">
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                        </span>
                                        <span class="stars-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="comment__body">
                                <div class="comment__author comment-author">
                                    <div class="comment-author__name">
                                        Konstantin Zhilin
                                    </div>
                                    <div class="comment-author__post">
                                        Chief Information Officer
                                    </div>
                                </div>

                                <div class="comment__text">
                                    <p>
                                        We have been using Perspective Studio
                                        for some time now for maintenance and
                                        development on our Magento 2 webshop,
                                        and we always feel that we are in good
                                        hands on every project with their team.
                                        We maintained open lines of
                                        communication and they listened at our
                                        wishes with a professional approach. For
                                        us, Perspective is the perfect partner
                                        in web development.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="comments__item comment">
                            <div class="comment__header">
                                <div class="comment__icon">
                                    <img
                                        src="{{media url='wysiwyg/Main/message/Group.png'}}"
                                        alt="C "
                                    />
                                </div>
                                <div class="comment__rate">
                                    <div class="comment__rate-number">
                                        <span>5.0</span>
                                    </div>
                                    <div class="comment__stars">
                                        <span class="stars-icons">
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                        </span>
                                        <span class="stars-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="comment__body">
                                <div class="comment__author comment-author">
                                    <div class="comment-author__name">
                                        Konstantin Zhilin
                                    </div>
                                    <div class="comment-author__post">
                                        Chief Information Officer
                                    </div>
                                </div>

                                <div class="comment__text">
                                    <p>
                                        We have been using Perspective Studio
                                        for some time now for maintenance and
                                        development on our Magento 2 webshop,
                                        and we always feel that we are in good
                                        hands on every project with their team.
                                        We maintained open lines of
                                        communication and they listened at our
                                        wishes with a professional approach. For
                                        us, Perspective is the perfect partner
                                        in web development.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="comments__item comment">
                            <div class="comment__header">
                                <div class="comment__icon">
                                    <img
                                        src="{{media url='wysiwyg/Main/message/Group.png'}}"
                                        alt="C "
                                    />
                                </div>
                                <div class="comment__rate">
                                    <div class="comment__rate-number">
                                        <span>5.0</span>
                                    </div>
                                    <div class="comment__stars">
                                        <span class="stars-icons">
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                        </span>
                                        <span class="stars-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="comment__body">
                                <div class="comment__author comment-author">
                                    <div class="comment-author__name">
                                        Konstantin Zhilin
                                    </div>
                                    <div class="comment-author__post">
                                        Chief Information Officer
                                    </div>
                                </div>

                                <div class="comment__text">
                                    <p>
                                        We have been using Perspective Studio
                                        for some time now for maintenance and
                                        development on our Magento 2 webshop,
                                        and we always feel that we are in good
                                        hands on every project with their team.
                                        We maintained open lines of
                                        communication and they listened at our
                                        wishes with a professional approach. For
                                        us, Perspective is the perfect partner
                                        in web development.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="comments__item comment">
                            <div class="comment__header">
                                <div class="comment__icon">
                                    <img
                                        src="{{media url='wysiwyg/Main/message/Group.png'}}"
                                        alt="C "
                                    />
                                </div>
                                <div class="comment__rate">
                                    <div class="comment__rate-number">
                                        <span>5.0</span>
                                    </div>
                                    <div class="comment__stars">
                                        <span class="stars-icons">
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                        </span>
                                        <span class="stars-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="comment__body">
                                <div class="comment__author comment-author">
                                    <div class="comment-author__name">
                                        Konstantin Zhilin
                                    </div>
                                    <div class="comment-author__post">
                                        Chief Information Officer
                                    </div>
                                </div>

                                <div class="comment__text">
                                    <p>
                                        We have been using Perspective Studio
                                        for some time now for maintenance and
                                        development on our Magento 2 webshop,
                                        and we always feel that we are in good
                                        hands on every project with their team.
                                        We maintained open lines of
                                        communication and they listened at our
                                        wishes with a professional approach. For
                                        us, Perspective is the perfect partner
                                        in web development.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </ul>

                    <div class="comments__controls">
                        <div
                            class="comments__arrow comments__arrow--prev"
                        ></div>
                        <div
                            class="comments__arrow comments__arrow--next"
                        ></div>
                    </div>
                    <div class="comments__reviews">
                        <span>4 rewiews</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main-certification">
        <div class="main-certification__container _container _grid-3-col">
            <div class="main-certification__section-label _section-label">
                Certification
            </div>
            <div class="main-certification__col">
                <h3 class="comments__title _sliding-text">
                    <span class="_sliding-text__line">Great projects</span> <br /><span
                      class="_sliding-text__line"
                      >requires great</span
                    >
                    <br /><span class="_sliding-text__line">engineers</span>
                </h3>
                <p class="main-certification__text _text-align-right">
                    We know how important adherence is. <br />
                    That’s why some of current certifications include:
                </p>
                <div
                    class="main-certification__adobe-achievments adobe-achievments"
                >
                    <ul class="adobe-achievments__list">
                        <li
                            class="adobe-achievments__item adobe-achievments__item--image-full"
                        >
                            <img
                                src="{{media url='wysiwyg/Main/Adobe.png'}}"
                                alt="adobe"
                            />
                        </li>

                        <li class="adobe-achievments__item">
                            <div class="adobe-achievments__image">
                                <img
                                    src="{{media url='wysiwyg/Main/Expert.png'}}"
                                    alt="prof"
                                />
                            </div>
                            <div class="adobe-achievments__body">
                                <div class="adobe-achievments__name">
                                    Adobe Certified Expert
                                </div>
                                <div class="adobe-achievments__text">
                                    Business Practitioner Developer
                                </div>
                            </div>
                        </li>

                        <li class="adobe-achievments__item">
                            <div class="adobe-achievments__image">
                                <img
                                    src="{{media url='wysiwyg/Main/Master.png'}}"
                                    alt="prof"
                                />
                            </div>
                            <div class="adobe-achievments__body">
                                <div class="adobe-achievments__name">
                                    Adobe Certified Master
                                </div>
                                <div class="adobe-achievments__text">
                                    Business Practitioner Developer
                                </div>
                            </div>
                        </li>

                        <li class="adobe-achievments__item">
                            <div class="adobe-achievments__image">
                                <img
                                    src="{{media url='wysiwyg/Main/Professional.png'}}"
                                    alt="prof"
                                />
                            </div>
                            <div class="adobe-achievments__body">
                                <div class="adobe-achievments__name">
                                    Adobe Certified Professional
                                </div>
                                <div class="adobe-achievments__text">
                                    Business Practitioner Developer
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="main-certification__col">
                <div class="main-certification__text--open-sans">
                    <p class="_text-align-right">
                        Also, we already have 8 certified developers and
                        solution specialist with 13 certificates for M1 and M2.
                    </p>
                </div>
                <div
                    class="main-certification__magento-achievments magento-achievments"
                >
                    <div class="magento-achievments__all">
                        <img
                            src="{{media url='wysiwyg/Main/all.png'}}"
                            alt="all"
                        />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
