<p>
    <a class="header__links--item" href="https://perspective.net.ua/company">Company</a> 
    <a class="header__links--item" href="https://perspective.net.ua/work">Work</a> 
    <a class="header__links--item" href="https://perspective.net.ua/services">Services</a> 
    <a class="header__links--item" href="https://perspective.net.ua/blog">Blog</a> 
    <a class="header__links--item" href="https://perspective.net.ua/contacts">Contacts</a>
</p>