<div class="careers-page">
    <div class="careers-page__intro ">
        <div class="careers-page__container _container _grid-3-col">
            <h1 class="h2 careers-page__title _page-title ">
                <p>Want to be part</p>
                <p>
                    of our <span class="_page-title--orange">magento</span> team?
                </p>
            </h1>
            <h2 class="h4 careers-page__sub-title _page-sub-title">The most important thing is the atmosphere in the team. For us, this is a state of constant development and growth, as well as family values, where everyone is friendly, caring and easy to communicate with.</h2>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--team ">
        <div class="careers-section__container _container  _grid-3-col">


            <div class="careers-section__section-label _section-label">Meet Our Team</div>

            <div class="careers-section__col">
                <h3 class="h3 careers-section__title">who we are</h3>
                <h5 class="h5 careers-section__text">Perspective is a Ukrainian, Magento-oriented team, with a bias towards the technical component of projects. We are represented in 4 cities: Kiev, Uzhgorod, Krivoy Rog and Shostka. </h5>
                <h5 class="h5 careers-section__text">Our clients are 70% Western companies (Europe and the USA) and 30% Ukrainian companies. Our goal is to be the best Magento experts.</h5>
            </div>

            <div class="careers-section__col">
                <div class="careers-section__squares careers-squares">
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">10</div>
                        <p class="careers-squares__text">front-end <br /> developers</p>
                    </div>
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">32</div>
                        <p class="careers-squares__text">back-end <br /> developers</p>
                    </div>
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">4</div>
                        <p class="careers-squares__text">DevOps <br /> & SysOps</p>
                    </div>
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">12</div>
                        <p class="careers-squares__text">QA engineers <br /> & team lead</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--benefits ">
        <div class="careers-section__container _container  _grid-3-col">
            <div class="careers-section__section-label _section-label">Benefits</div>
            <div class="careers-section__cell">
                <h3 class="h3 careers-section__title">What we offer</h3>
                <h5 class="h5 careers-section__text">The most important thing is the atmosphere in the team. For us, this is a state of constant development and growth, as well as family values, where everyone is friendly, caring and easy to communicate with.</h5>

                <div class="_h4">Magento expertise</div>
                <ul class="careers-section__list _list">
                    <li>We hold internal and external Magento meetups, upgrade our speakers and invite external experts.</li>
                    <li>We drive the spirit of constant development - weekly Magento meetings and full preparation of each employee for certification.</li>
                </ul>
            </div>
            <div class="careers-section__cell">
                <div class="careers-section__image">
                    <img loading="lazy" src="{{media url='wysiwyg/careers/3Z_2009.w020.n001.635B.p15.635_Converted_1.png'}}" alt="">
                </div>
            </div>

            <div class="careers-section__empty-cell"></div>
            <div class="careers-section__cell">
                <div class="_h4">Professional and personal growth</div>
                <ul class="careers-section__list _list">
                    <li>We provide vertical growth. </li>
                    <li>The staff has a teacher in Magento development and in English.</li>
                    <li>Sometimes, to expand the team, we conduct public Magento courses at the university.</li>
                    <li>You can count on partial or full compensation for training - courses, conferences, meetups, etc.</li>
                    <li>You will have access to an internal offline and online library, which contains professional literature for all specialists.</li>
                </ul>

                <div class="careers-section__image careers-section__image--desktop">
                    <img loading="lazy" src="{{media url='wysiwyg/careers/2109.w032.n003.103B.p1.103_Converted_1.png'}}" alt="">
                </div>
            </div>
            <div class="careers-section__cell">
                <div class="_h4">Work & Life balance</div>
                <p>Despite the fact that our clients are distributed all over the world, we have a standardized schedule. We do our best to avoid overtime. But even if they happen, your time will be paid by the coefficient.</p>
                <div class="_h4">salary</div>
                <ul class="careers-section__list _list">
                    <li>Regular reviews, at least twice a year, as well as after Magento certification</li>
                    <li>Referral program - bonus for recommending a future colleague</li>
                    <li>Partial tax refund</li>
                    <li>24 working days of vacation</li>
                    <li>20 working days sick leave</li>
                </ul>

                <div class="_h4">Gamification</div>
                <p>Gamification - by performing certain actions, earn internal currency and exchange it for corporate merchandise or other goodies from the company</p>
                <div class="careers-section__image careers-section__image--mobile">
                    <img loading="lazy" src="{{media url='wysiwyg/careers/2109.w032.n003.103B.p1.103_Converted_1.png'}}" alt="">
                </div>
            </div>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--join-us">
        <div class="careers-section__container _container  _grid-2-col">
            <div class="careers-section__section-label _section-label">Join us!</div>
            <div class="careers-section__content">
                <h3 class="h3 careers-section__title">We are <br /> looking for</h3>

                <div class="careers-section__collapsible careers-collapsible" x-data="{selected:null}">
                    <!-- 1 -->
                    <div data-role="collapsible" 
                         class="careers-collapsible__item"
                         :class="{'active': selected == 1}"
                    >
                        <div data-role="trigger" 
                             class="careers-collapsible__trigger"
                             @click="selected !== 1 ? selected = 1 : selected = null"
                        >
                            <div class="careers-collapsible__header">
                                <h4 class="h4 careers-collapsible__title">Business Development Manager</h4>
                                <p class="careers-collapsible__locate">Kyiv</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>
                        </div>

                    </div>
                    <div data-role="content"
                         style="" 
                         x-ref="container1" 
                         x-bind:style="selected == 1 ? 'max-height: ' + $refs.container1.scrollHeight + 'px' : ''"
                    >
                        <div class="careers-collapsible__content">
                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__text">Looking for a high-performing and self-motivated individual, to help us meet our customer acquisition and revenue growth targets. Will be responsible for maximizing our sales team potential, crafting sales plans. Our perfect candidate will try to understand all the business challenges of his potential client and he knows that he is not selling technical specialists, but offers comprehensive solutions for his partners.</h5>
                                <a href="#footer-alt" class="_scrollTo careers-collapsible__button careers-collapsible__button--desktop _button _button--orange-bg" style="width:fit-content;">
                                    <span class="_button__text">Send your CV</span>
                                    <span class="_button__overlay _button__overlay--hover"></span>
                                    <span class="_button__overlay _button__overlay--active"></span>
                                </a>
                            </div>

                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__list-legend">Main Responsibilities :</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>Creating strategies for sales growth in alignment to company’s goals</li>
                                    <li>The medium and large-sized enterprise client acquisition</li>
                                    <li>Act as the main commercial contact for new enterprise clients and establish productive, professional relationships with them;</li>
                                    <li>Develop new business avenues and relations</li>
                                    <li>Generate proposals / contracts for clients and ensure compliance with support of Pre-sales team</li>
                                    <li>Being brand ambassador of company</li>
                                    <li>Representing company at various exhibition and trade fairs</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Skills Required:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>At least 3+ years with similar experience in the IT industry</li>
                                    <li>Proven track record of exceeding quotas of $100k in signings or more</li>
                                    <li>Ability to interact with high-level Executives, convey the value proposition of the Perspective services to take over new business and opportunities</li>
                                    <li>Experience in selling projects / solutions for web development, e-commerce, mobile;</li>
                                    <li>Successful experience in sites such as LinkedIn and similar;</li>
                                    <li>Understanding of the entire sales process and software development process</li>
                                    <li>Consistent track record of selling software into large Enterprise accounts and achieving personal and team goals.</li>
                                    <li>Written and spoken English — Advanced level</li>
                                    <li>Ability to meet deadlines</li>
                                    <li>Willingness to travel</li>
                                </ul>
                            </div>

                            <a href="#footer-alt" class="_scrollTo careers-collapsible__button careers-collapsible__button--mobile _button _button--orange-bg" style="text-align:center;">
                                <span class="_button__text">Send your CV</span>
                                <span class="_button__overlay _button__overlay--hover"></span>
                                <span class="_button__overlay _button__overlay--active"></span>
                            </a>

                        </div>
                    </div>

                    <!-- 2 -->
                    <div data-role="collapsible" 
                         class="careers-collapsible__item"
                         :class="{'active': selected == 2}"
                    >
                        <div data-role="trigger" 
                             class="careers-collapsible__trigger"
                             @click="selected !== 2 ? selected = 2 : selected = null"
                        >
                            <div class="careers-collapsible__header">
                                <h4 class="h4 careers-collapsible__title">Business Analyst</h4>
                                <p class="careers-collapsible__locate">Kyiv</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>
                        </div>

                    </div>
                    <div data-role="content"
                         style="" 
                         x-ref="container2" 
                         x-bind:style="selected == 2 ? 'max-height: ' + $refs.container2.scrollHeight + 'px' : ''"
                    >
                        <div class="careers-collapsible__content">
                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__text">
                                    Our team specializes in an integrated approach to web development and graphics services. The key area of ​​e-commerce. We are also growing in search of a new motivated and purposeful Business Analyst that will join our best Magento Team.
                                </h5>
                                <a href="#footer-alt" class="_scrollTo careers-collapsible__button careers-collapsible__button--desktop _button _button--orange-bg" style="width:fit-content;">
                                    <span class="_button__text">Send your CV</span>
                                    <span class="_button__overlay _button__overlay--hover"></span>
                                    <span class="_button__overlay _button__overlay--active"></span>
                                </a>
                            </div>

                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__list-legend">Responsibilities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>identify product requirements and business needs from the scratch;</li>
                                    <li>evaluation of business processes, the anticipation of requirements, identification of areas for improvement, development, and implementation of solutions;</li>
                                    <li>priority of initiatives based on business needs and requirements;</li>
                                    <li>act as an expert on product-related issues and inquiries that may arise;</li>
                                    <li>risk management;</li>
                                    <li>monitoring results and ensuring timely completion of projects.</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Required skills:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>1,5 years of experience in BA;</li>
                                    <li>work experience with clients from the USA, Great Britain, or Europe;</li>
                                    <li>understanding the website development process/staging;</li>
                                    <li>understanding of applied technologies (web);</li>
                                    <li>Upper-Intermediate or higher English level.</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Will be an advantage:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>experience in web design/e-commerce/software development.</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Requirements for personal qualities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>the ability to keep your work organized;</li>
                                    <li>punctuality and responsibility;</li>
                                    <li>teamwork skills and initiative;</li>
                                    <li>attention to details;</li>
                                    <li>analytical mindset and agility</li>
                                </ul>
                            </div>

                            <a href="#footer-alt" class="_scrollTo careers-collapsible__button careers-collapsible__button--mobile _button _button--orange-bg" style="text-align:center;">
                                <span class="_button__text">Send your CV</span>
                                <span class="_button__overlay _button__overlay--hover"></span>
                                <span class="_button__overlay _button__overlay--active"></span>
                            </a>

                        </div>
                    </div>

                    <!-- 3 -->
                    <div data-role="collapsible" 
                         class="careers-collapsible__item"
                         :class="{'active': selected == 3}"
                    >
                        <div data-role="trigger" 
                             class="careers-collapsible__trigger"
                             @click="selected !== 3 ? selected = 3 : selected = null"
                        >
                            <div class="careers-collapsible__header">
                                <h4 class="h4 careers-collapsible__title">Project Manager</h4>
                                <p class="careers-collapsible__locate">Kyiv</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>
                        </div>

                    </div>
                    <div data-role="content"
                         style="" 
                         x-ref="container3" 
                         x-bind:style="selected == 3 ? 'max-height: ' + $refs.container3.scrollHeight + 'px' : ''"
                    >
                        <div class="careers-collapsible__content">
                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__text">
                                    Our team specializes in an integrated approach to web development and graphics services. The key area of ​​e-commerce. We are also growing in search of a new motivated and purposeful PM that will join our best Magento Team.
                                </h5>
                                <a href="#footer-alt" class="_scrollTo careers-collapsible__button careers-collapsible__button--desktop _button _button--orange-bg" style="width:fit-content;">
                                    <span class="_button__text">Send your CV</span>
                                    <span class="_button__overlay _button__overlay--hover"></span>
                                    <span class="_button__overlay _button__overlay--active"></span>
                                </a>
                            </div>

                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__list-legend">Responsibilities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>communication with stakeholders to identify the business needs;</li>
                                    <li>writing technical documentation for the project;</li>
                                    <li>advice, recommendations, and suggestions for improving the customer concept;</li>
                                    <li>coordination of the budget with the client and its control;</li>
                                    <li>sprint planning, maintaining a backlog of project tasks;</li>
                                    <li>setting tasks for the development team, monitoring the compliance of the developed functionality concerning the technical specifications and customer requirements</li>
                                    <li>people management of the development team;</li>
                                    <li>management of risks;</li>
                                    <li>participation in the delivery of the product to production environment.</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Required skills:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>1,5 years of experience in PM or BA;</li>
                                    <li>understanding the website development process/staging;</li>
                                    <li>understanding of applied technologies (web);</li>
                                    <li>Upper-Intermediate or higher English level.</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Will be an advantage:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>experience in similar positions in similar companies.</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Requirements for personal qualities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>the ability to keep your work organized;</li>
                                    <li>punctuality and responsibility;</li>
                                    <li>teamwork skills and initiative;</li>
                                    <li>attention to details;</li>
                                    <li>analytical mindset and agility</li>
                                </ul>
                            </div>

                            <a href="#footer-alt" class="_scrollTo careers-collapsible__button careers-collapsible__button--mobile _button _button--orange-bg" style="text-align:center;">
                                <span class="_button__text">Send your CV</span>
                                <span class="_button__overlay _button__overlay--hover"></span>
                                <span class="_button__overlay _button__overlay--active"></span>
                            </a>

                        </div>
                    </div>

                    <!-- 4 -->
                    <div data-role="collapsible" 
                         class="careers-collapsible__item"
                         :class="{'active': selected == 4}"
                         >
                        <div data-role="trigger" 
                             class="careers-collapsible__trigger"
                             @click="selected !== 4 ? selected = 4 : selected = null"
                        >
                            <div class="careers-collapsible__header">
                                <h4 class="h4 careers-collapsible__title">Magento BackEnd Developer</h4>
                                <p class="careers-collapsible__locate">Uzhhorod, Shostka, Kryvyi Rih, Cherkasy</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>
                        </div>

                    </div>
                    <div data-role="content"
                         style="" 
                         x-ref="container4" 
                         x-bind:style="selected == 4 ? 'max-height: ' + $refs.container4.scrollHeight + 'px' : ''"
                    >
                        <div class="careers-collapsible__content">
                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__text">
                                    Our team specializes in an integrated approach to web development and graphics services. The key area of ​​e-commerce. We are also growing in search of a new motivated and purposeful BackEnd Developer that will join our best Magento Team.
                                </h5>
                                <a href="#footer-alt" class="_scrollTo careers-collapsible__button careers-collapsible__button--desktop _button _button--orange-bg" style="width:fit-content;">
                                    <span class="_button__text">Send your CV</span>
                                    <span class="_button__overlay _button__overlay--hover"></span>
                                    <span class="_button__overlay _button__overlay--active"></span>
                                </a>
                            </div>

                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__list-legend">Approximate responsibilities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>websites development on Magento from scratch;</li>
                                    <li>finalization of existing sites on Magento.</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Required skills:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>1,5−2 years of development experience with Magento;</li>
                                    <li>PHP, SQL – high level;</li>
                                    <li>HTML, CSS – middle level;</li>
                                    <li>MVC, SVN – understanding;</li>
                                    <li>understanding of the whole web development process.</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Will be an advantage:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>Pre-intermediate or higher English level;</li>
                                    <li>Zend Framework;</li>
                                    <li>NoSQL, jQuery, Git.</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Requirements for personal qualities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>the ability to keep your work in a structured form;</li>
                                    <li>the ability to plan and evaluate your tasks.</li>
                                </ul>
                            </div>

                            <a href="#footer-alt" class="_scrollTo careers-collapsible__button careers-collapsible__button--mobile _button _button--orange-bg" style="text-align:center;">
                                <span class="_button__text">Send your CV</span>
                                <span class="_button__overlay _button__overlay--hover"></span>
                                <span class="_button__overlay _button__overlay--active"></span>
                            </a>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>