<div class="careers-page">
    <div class="careers-page__intro">
        <div class="careers-page__container _container _grid-3-col">
            <h1 class="h2 careers-page__title _page-title">
                <p>Want to be part</p>
                <p>of our <span class="_page-title--orange">magento</span> team?</p>
            </h1>
            <h2 class="h4 careers-page__sub-title _page-sub-title">
                The most important thing is the atmosphere in the team. For us, this is a state of constant development and
                growth, as well as family values, where everyone is friendly, caring and easy to communicate with.
            </h2>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--team">
        <div class="careers-section__container _container _grid-3-col">
            <div class="careers-section__section-label _section-label">Meet Our Team</div>

            <div class="careers-section__col">
                <h3 class="h3 careers-section__title">who we are</h3>
                <h5 class="h5 careers-section__text">
                    Perspective is a Ukrainian, Magento-oriented team, with a bias towards the technical component of projects. We
                    are represented in 5 cities: Kyiv, Uzhhorod, Kryvyi Rih, Cherkasy and Shostka.
                </h5>
                <h5 class="h5 careers-section__text">
                    Our clients are 70% Western companies (Europe and the USA) and 30% Ukrainian companies. Our goal is to be the
                    best Magento experts.
                </h5>
            </div>

            <div class="careers-section__col">
                <div class="careers-section__squares careers-squares">
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">10</div>
                        <p class="careers-squares__text">
                            front-end <br />
                            developers
                        </p>
                    </div>
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">32</div>
                        <p class="careers-squares__text">
                            back-end <br />
                            developers
                        </p>
                    </div>
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">4</div>
                        <p class="careers-squares__text">
                            DevOps <br />
                            & SysOps
                        </p>
                    </div>
                    <div class="careers-squares__item">
                        <div class="careers-squares__digit">12</div>
                        <p class="careers-squares__text">QA engineers</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--growth company-growth _container">
        <div class="company-growth__body _grid-2-col">
            <div class="company-growth__label _section-label">Growth</div>
            <div class="company-growth__content">
                <div class="company-growth__top">
                    <h5 class="h5 company-growth__text">
                        Our company was founded in 2009 and initially dealt with different CMS and Frameworks. Still, after some
                        time, we realized that we should have a definite aim to develop ourselves in one thing, mastering skills in
                        a narrow area.
                    </h5>
                    <h5 class="h5 company-growth__text _text-align-right">
                        Perspective Studio has seen constant annual growth and success since its inception. We currently have five
                        offices in Kyiv, Uzhhorod, Shostka, Cherkasy, and Kryvyi Rih.
                    </h5>
                </div>
                <div class="company-growth__bottom">
                    <h3 class="h3 company-growth__title">
                        Our aim is to become <span class="company-growth__title--orange">the Best</span> Magento Team ever
                    </h3>
                    <div class="company-growth__image company-map-image" data-mage-init='{"companyImageAnimation" : {}}'>
                        <div class="company-map-image__container">
                            <div class="highlight" style="width: 100%">
                                <img loading="lazy" src="{{media url='wysiwyg/company/map/highlight.svg'}}" alt="hover" />
                            </div>
                            <div class="ukraine" style="width: 100%">
                                <img loading="lazy" src="{{media url='wysiwyg/company/map/ukraine.svg'}}" alt="hover" />
                            </div>
                            <div class="uzh">
                                <img loading="lazy" src="{{media url='wysiwyg/company/map/uzh.svg'}}" alt="hover" />
                            </div>
                            <div class="shost">
                                <img loading="lazy" src="{{media url='wysiwyg/company/map/shost.svg'}}" alt="hover" />
                            </div>
                            <div class="kyiv">
                                <img loading="lazy" src="{{media url='wysiwyg/company/map/kyiv.svg'}}" alt="hover" />
                            </div>
                            <div class="kr">
                                <img loading="lazy" src="{{media url='wysiwyg/company/map/kr.svg'}}" alt="hover" />
                            </div>
                            <div class="cher">
                                <img loading="lazy" src="{{media url='wysiwyg/company/map/cher.svg'}}" alt="hover" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--benefits">
        <div class="careers-section__container _container _grid-3-col">
            <div class="careers-section__section-label _section-label">Benefits</div>
            <div class="careers-section__cell">
                <h3 class="h3 careers-section__title">What we offer</h3>
                <h5 class="h5 careers-section__text">
                    The most important thing is the atmosphere in the team. For us, this is a state of constant development and
                    growth, as well as family values, where everyone is friendly, caring and easy to communicate with.
                </h5>

                <div class="_h4">Magento expertise</div>
                <ul class="careers-section__list _list">
                    <li>We hold internal and external Magento meetups, upgrade our speakers and invite external experts.</li>
                    <li>
                        We drive the spirit of constant development - weekly Magento meetings and full preparation of each employee
                        for certification.
                    </li>
                </ul>
            </div>
            <div class="careers-section__cell">
                <div class="careers-section__image">
                    <img
                            loading="lazy"
                            src="{{media url='wysiwyg/careers/3Z_2009.w020.n001.635B.p15.635_Converted_1.png'}}"
                            alt="Magento Web Design"
                    />
                </div>
            </div>

            <div class="careers-section__empty-cell"></div>
            <div class="careers-section__cell">
                <div class="_h4">Professional and personal growth</div>
                <ul class="careers-section__list _list">
                    <li>We provide vertical growth.</li>
                    <li>The staff has a teacher in Magento development and in English.</li>
                    <li>Sometimes, to expand the team, we conduct public Magento courses at the university.</li>
                    <li>You can count on partial or full compensation for training - courses, conferences, meetups, etc.</li>
                    <li>
                        You will have access to an internal offline and online library, which contains professional literature for
                        all specialists.
                    </li>
                </ul>

                <div class="careers-section__image careers-section__image--desktop">
                    <img loading="lazy" src="{{media url='wysiwyg/careers/2109.w032.n003.103B.p1.103_Converted_1.png'}}" alt="Experienced Magento Developer" />
                </div>
            </div>
            <div class="careers-section__cell">
                <div class="_h4">Work & Life balance</div>
                <p>
                    Despite the fact that our clients are distributed all over the world, we have a standardized schedule. We do
                    our best to avoid overtime. But even if they happen, your time will be paid by the coefficient.
                </p>
                <div class="_h4">salary</div>
                <ul class="careers-section__list _list">
                    <li>Regular reviews, at least twice a year, as well as after Magento certification</li>
                    <li>Referral program - bonus for recommending a future colleague</li>
                    <li>Partial tax refund</li>
                    <li>24 working days of vacation</li>
                    <li>20 working days sick leave</li>
                </ul>

                <div class="_h4">Gamification</div>
                <p>
                    Gamification - by performing certain actions, earn internal currency and exchange it for corporate merchandise
                    or other goodies from the company
                </p>
                <div class="careers-section__image careers-section__image--mobile">
                    <img loading="lazy" src="{{media url='wysiwyg/careers/2109.w032.n003.103B.p1.103_Converted_1.png'}}" alt="Experienced Magento Developer" />
                </div>
            </div>
        </div>
    </div>

    <div class="careers-page__section careers-section careers-section--join-us">
        <div class="careers-section__container _container _grid-2-col">
            <div class="careers-section__section-label _section-label">Join us!</div>
            <div class="careers-section__content">
                <h3 class="h3 careers-section__title">
                    We are <br />
                    looking for
                </h3>

                <div class="careers-section__collapsible careers-collapsible" x-data="{selected:null}">
                    <!-- 1 -->
                    <div data-role="collapsible" class="careers-collapsible__item" :class="{'active': selected == 1}">
                        <div
                                data-role="trigger"
                                class="careers-collapsible__trigger"
                                @click="selected !== 1 ? selected = 1 : selected = null"
                        >
                            <div class="careers-collapsible__header">
                                <h4 class="h4 careers-collapsible__title">Project Manager</h4>
                                <p class="careers-collapsible__locate">Kyiv</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>
                        </div>
                    </div>
                    <div
                            data-role="content"
                            style=""
                            x-ref="container1"
                            x-bind:style="selected == 1 ? 'max-height: ' + $refs.container2.scrollHeight + 'px' : ''"
                    >
                        <div class="careers-collapsible__content">
                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__text">
                                    Our team specializes in an integrated approach to web development and graphics services. The key area
                                    of ​​e-commerce. We are also growing in search of a new motivated and purposeful Business Analyst that
                                    will join our best Magento Team.
                                </h5>
                                <a
                                        href="#footer-alt"
                                        class="_scrollTo careers-collapsible__button careers-collapsible__button--desktop _button _button--orange-bg"
                                        style="width: fit-content"
                                >
                                    <span class="_button__text">Send your CV</span>
                                    <span class="_button__overlay _button__overlay--hover"></span>
                                    <span class="_button__overlay _button__overlay--active"></span>
                                </a>
                            </div>

                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__list-legend">Responsibilities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>Communication with stakeholders to identify the business needs</li>
                                    <li>Writing technical documentation for the project</li>
                                    <li>Advice, recommendations, and suggestions for improving the customer concept</li>
                                    <li>Coordination of the budget with the client and its control</li>
                                    <li>Sprint planning, maintaining a backlog of project tasks</li>
                                    <li>Setting tasks for the development team, monitoring the compliance of the developed</li>
                                    <li>People management of the development team</li>
                                    <li>Management of risks</li>
                                    <li>Participation in the delivery of the product to production environment</li>

                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Required skills:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>2 years of experience in PM or BA in web development</li>
                                    <li>Understanding the website development process/staging</li>
                                    <li>Understanding of applied technologies (web)</li>
                                    <li>Upper-Intermediate or higher English level</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Will be an advantage:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>experience in similar positions in similar companies</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Requirements for personal qualities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>The ability to keep your work organized;</li>
                                    <li>Punctuality and responsibility;</li>
                                    <li>Teamwork skills and initiative;</li>
                                    <li>Attention to details;</li>
                                    <li>Analytical mindset and agility</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">We offer:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>Career growth opportunity (growth from Junior to Senior — salary as a result)</li>
                                    <li>Work from the office in Kyiv</li>
                                    <li>The opportunity to learn from Senior PM, in the future to become a Business Analyst (possible rotation)</li>
                                    <li>You will be able to manage projects independently, act as a Product Manager, make decisions on the project</li>
                                    <li>Work with very complex tasks, invaluable technical skills</li>
                                    <li>We have well-established and described processes in the company</li>
                                    <li>Joint attendance at conferences, corporate events, and payment for Magento certification</li>
                                    <li>Paid holidays, sick leaves, cookies, etc.</li>
                                </ul>
                            </div>

                            <a
                                    href="#footer-alt"
                                    class="_scrollTo careers-collapsible__button careers-collapsible__button--mobile _button _button--orange-bg"
                                    style="text-align: center"
                            >
                                <span class="_button__text">Send your CV</span>
                                <span class="_button__overlay _button__overlay--hover"></span>
                                <span class="_button__overlay _button__overlay--active"></span>
                            </a>
                        </div>
                    </div>

                    <!-- 2 -->
                    <div data-role="collapsible" class="careers-collapsible__item" :class="{'active': selected == 2}">
                        <div
                                data-role="trigger"
                                class="careers-collapsible__trigger"
                                @click="selected !== 2 ? selected = 2 : selected = null"
                        >
                            <div class="careers-collapsible__header">
                                <h4 class="h4 careers-collapsible__title">Junior Front-End Developer</h4>
                                <p class="careers-collapsible__locate">Kryvyi Rih</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>
                        </div>
                    </div>
                    <div
                            data-role="content"
                            style=""
                            x-ref="container2"
                            x-bind:style="selected == 2 ? 'max-height: ' + $refs.container2.scrollHeight + 'px' : ''"
                    >
                        <div class="careers-collapsible__content">
                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__text">
                                    Our team specializes in an integrated approach to web development and graphics services. The key area of ​​e-commerce. We are also growing in search of a new motivated and purposeful Front-End Developer that will join our best Magento Team.
                                </h5>
                                <a
                                        href="#footer-alt"
                                        class="_scrollTo careers-collapsible__button careers-collapsible__button--desktop _button _button--orange-bg"
                                        style="width: fit-content"
                                >
                                    <span class="_button__text">Send your CV</span>
                                    <span class="_button__overlay _button__overlay--hover"></span>
                                    <span class="_button__overlay _button__overlay--active"></span>
                                </a>
                            </div>

                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__list-legend">Required skills:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>0,5−1 year of development experience</li>
                                    <li>XML</li>
                                    <li>Cross-browser HTML + CSS, HTML5, CSS3 (LESS, SASS (SCSS)), html templating</li>
                                    <li>JS (basic knowledge of JQuery, JQuery widgets, Knockout.js, RequireJS), understanding of the concept of OOP in JS</li>
                                    <li>Understanding of SDLC, Agile methodologies (SCRUM, Kanban)</li>
                                    <li>Bootstrap</li>
                                    <li>Grunt/Gulp</li>
                                    <li>Experience with Jira (Confluence, Jira applets)</li>
                                    <li>GIT</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Will be an advantage:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>Knowledge and using ES6</li>
                                    <li>Experience with JavaScript frameworks (React+Redux/Vue+Vuex)</li>
                                    <li>Basic knowledge of PHP</li>
                                    <li>Basic English (at the reading level)</li>
                                    <li>Experience with Magento 1 and Magento 2</li>
                                    <li>Knowledge of graphic editors (Photoshop, Illustrator, Sketch, Avocode, etc.)</li>
                                    <li>Experience with GraphQL or RESTful API</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Requirements for personal qualities:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>Higher technical education</li>
                                    <li>Ability to quickly learn independently and fill in gaps in knowledge</li>
                                    <li>Independence and ability to select, study and implement new, more optimal approaches</li>
                                    <li>to solving standard and non-standard tasks</li>
                                </ul>
                            </div>

                            <a
                                    href="#footer-alt"
                                    class="_scrollTo careers-collapsible__button careers-collapsible__button--mobile _button _button--orange-bg"
                                    style="text-align: center"
                            >
                                <span class="_button__text">Send your CV</span>
                                <span class="_button__overlay _button__overlay--hover"></span>
                                <span class="_button__overlay _button__overlay--active"></span>
                            </a>
                        </div>
                    </div>

                    <!-- 4 -->
                    <div data-role="collapsible" class="careers-collapsible__item" :class="{'active': selected == 4}">
                        <div
                                data-role="trigger"
                                class="careers-collapsible__trigger"
                                @click="selected !== 4 ? selected = 4 : selected = null"
                        >
                            <div class="careers-collapsible__header">
                                <h4 class="h4 careers-collapsible__title">QA Engineer</h4>
                                <p class="careers-collapsible__locate">Kryvyi Rih</p>
                            </div>
                            <span class="careers-collapsible__plus-sign"></span>
                        </div>
                    </div>
                    <div
                            data-role="content"
                            style=""
                            x-ref="container4"
                            x-bind:style="selected == 4 ? 'max-height: ' + $refs.container4.scrollHeight + 'px' : ''"
                    >
                        <div class="careers-collapsible__content">
                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__text">
                                    Our team specializes in an integrated approach to web development and graphics services. The key area of ​​e-commerce. We are also growing in search of a new motivated and purposeful QA engineer that will join our best Magento Team.
                                </h5>
                                <a
                                        href="#footer-alt"
                                        class="_scrollTo careers-collapsible__button careers-collapsible__button--desktop _button _button--orange-bg"
                                        style="width: fit-content"
                                >
                                    <span class="_button__text">Send your CV</span>
                                    <span class="_button__overlay _button__overlay--hover"></span>
                                    <span class="_button__overlay _button__overlay--active"></span>
                                </a>
                            </div>

                            <div class="careers-collapsible__col">
                                <h5 class="h5 careers-collapsible__list-legend">Responsibilitiess:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>Manual testing of ready-made websites</li>
                                    <li>Development, updating of test documentation and work with it</li>
                                    <li>Creation and execution of test scenarios</li>
                                    <li>Support and creation of technical documentation</li>
                                    <li>Creation of TEST\USE Cases documentation</li>
                                    <li>Communication with developers and QA at all stages of testing</li>
                                    <li>Plan and estimate the timing of testing activities</li>

                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Required skills:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>At least 6 months of experience</li>
                                    <li>Understanding of the software development cycle and quality control</li>
                                    <li>Experience with JIRA</li>
                                    <li>White, gray, black - box, regression, penetration testing</li>
                                    <li>Testing according to the technical specifications</li>
                                    <li>Ability to quickly switch between tasks and effectively allocate time between them</li>
                                    <li>Knowledge of the principles of Scrum, Agile</li>
                                    <li>Knowledge of HTML, CSS, JavaScript</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">Will be an advantage:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>Knowledge of Protractor, Selenium frameworks</li>
                                    <li>Automation of testing processes</li>
                                    <li>Experience with Git, Apache JMeter</li>
                                </ul>

                                <h5 class="h5 careers-collapsible__list-legend">We offer:</h5>
                                <ul class="careers-collapsible__list _list">
                                    <li>Comfortable working conditions and decent compensation</li>
                                    <li>The opportunity to work with the best development team</li>
                                    <li>We have a strong culture and high requirements for the professional qualities of our people</li>
                                    <li>We value talent more than experience, and we create conditions for the realization of these talents</li>
                                    <li>Work schedule: from Monday to Friday, from 9 to 18</li>
                                    <li>Work from the office in Kryvyi Rih</li>
                                    <li>Paid vacation, sick leave, cookies, etc</li>
                                </ul>
                            </div>

                            <a
                                    href="#footer-alt"
                                    class="_scrollTo careers-collapsible__button careers-collapsible__button--mobile _button _button--orange-bg"
                                    style="text-align: center"
                            >
                                <span class="_button__text">Send your CV</span>
                                <span class="_button__overlay _button__overlay--hover"></span>
                                <span class="_button__overlay _button__overlay--active"></span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
