<div class="extensions-page">
    <div class="extensions-page__container _container">
        <div class="extensions-page__top _grid-3-col">
            <h1 class="h2 extensions-page__title _sliding-text">
                <span class="_sliding-text__line">Custom magento<br /> </span>
                <span class="_sliding-text__line">extensions </span>
            </h1>
            <h2 class="h4 extensions-page__sub-title">
                At Perspective, we pride ourselves on being more than just a Magento development agency. With over a decade of experience and a team of dedicated
                Magento experts, we specialize in crafting custom Magento and Magento 2 extensions that push the boundaries of what's possible with your eCommerce
                store. Our extensions are designed to improve efficiency, enhance user experience, and drive sales, ensuring your business stands out in the
                competitive digital landscape.
            </h2>
        </div>

        <div
            class="extensions-page__squares extensions-squares"
            itemscope
            itemtype="https://schema.org/BreadcrumbList"
        >
            <div class="extensions-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <img src="{{media url='wysiwyg/extensions/icon-payment.svg'}}" alt="LiqPAY, PrivatBank Parts Payment and PrivatBank Instant Installment." />
                <div class="extensions-squares__text">
                    <div class="extensions-squares__title">
                        LiqPAY, PrivatBank Parts Payment and PrivatBank Instant Installment.
                    </div>
                    <div class="extensions-squares__description">
                        Extension for LiqPay, a payment service that provides Internet acquiring features - accepting payments on websites, in mobile applications
                        connected to the Internet.
                    </div>
                </div>

                <a href="https://github.com/PerspectiveTeam/m2payment">
                    <button type="button" class="service-section__button _button _button--arrow">
                        <span class="_button__text"> View on Github </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> View on Github </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
                <meta itemprop="position" content="1" />
            </div>
            <div class="extensions-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <img src="{{media url='wysiwyg/extensions/icon-nova-poshta.svg'}}" alt="Nova Poshta" />
                <div class="extensions-squares__text">
                    <div class="extensions-squares__title">
                        Nova Poshta
                    </div>
                    <div class="extensions-squares__description">
                        Extension for Nova Poshta, a Ukrainian company which is the leader in express delivery.
                    </div>
                </div>

                <a href="https://github.com/PerspectiveTeam/NovaposhtaShipping">
                    <button type="button" class="service-section__button _button _button--arrow">
                        <span class="_button__text"> View on Github </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> View on Github </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
                <meta itemprop="position" content="1" />
            </div>
            <div class="extensions-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <img src="{{media url='wysiwyg/extensions/icon-lighthouse-snapshots.svg'}}" alt="Lighthouse Snapshots" />
                <div class="extensions-squares__text">
                    <div class="extensions-squares__title">
                        Lighthouse Snapshots
                    </div>
                    <div class="extensions-squares__description">
                        Lighthouse Snapshorts leverage a variety of tools and libraries for performance analysis, web development, and admin panel improvements,
                        making it a valuable addition to Magento 2 installations seeking to optimize their store's performance and management capabilities.
                    </div>
                </div>

                <a href="https://github.com/PerspectiveTeam/Lighthouse">
                    <button type="button" class="service-section__button _button _button--arrow">
                        <span class="_button__text"> View on Github </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> View on Github </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
                <meta itemprop="position" content="1" />
            </div>
            <div class="extensions-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <img src="{{media url='wysiwyg/extensions/icon-portmone-payment.svg'}}" alt="Portmone Payment" />
                <div class="extensions-squares__text">
                    <div class="extensions-squares__title">
                        Portmone Payment
                    </div>
                    <div class="extensions-squares__description">
                        Extension for Portmone, a Ukrainian online payment system that allows users to pay for various services online, such as utility bills,
                        mobile phone charges, and internet services, among others, in a secure and convenient manner.
                    </div>
                </div>

                <a href="https://github.com/PerspectiveTeam/m2portmone-preauth">
                    <button type="button" class="service-section__button _button _button--arrow">
                        <span class="_button__text"> View on Github </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> View on Github </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
                <meta itemprop="position" content="1" />
            </div>
            <div class="extensions-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <img src="{{media url='wysiwyg/extensions/icon-resolve-payment.svg'}}" alt="Resolve Payment" />
                <div class="extensions-squares__text">
                    <div class="extensions-squares__title">
                        Resolve Payment
                    </div>
                    <div class="extensions-squares__description">
                        Extension for Resolve, a B2B payments platform that offers buy now, pay later billing for business purchases.
                    </div>
                </div>

                <a href="https://commercemarketplace.adobe.com/media/catalog/product/resolve-magento2-2-1-6-ce/installation_guides.pdf">
                    <button type="button" class="service-section__button _button _button--arrow">
                        <span class="_button__text"> View on Github </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> View on Github </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
                <meta itemprop="position" content="1" />
            </div>
            <div class="extensions-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <img src="{{media url='wysiwyg/extensions/icon-climate-friendly-cart.svg'}}" alt="Climate Friendly Cart" />
                <div class="extensions-squares__text">
                    <div class="extensions-squares__title">
                        Climate Friendly Cart
                    </div>
                    <div class="extensions-squares__description">
                        With our Climate Friendly Cart, your customers can fight climate change by offsetting the carbon footprint of their purchases.
                    </div>
                </div>

                <a href="https://commercemarketplace.adobe.com/carbonclick-climate-friendly-cart.html">
                    <button type="button" class="service-section__button _button _button--arrow">
                        <span class="_button__text"> View on Github </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> View on Github </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
                <meta itemprop="position" content="1" />
            </div>
            <div class="extensions-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <img src="{{media url='wysiwyg/extensions/icon-press-loft-affiliate.svg'}}" alt="Press Loft Affiliate" />
                <div class="extensions-squares__text">
                    <div class="extensions-squares__title">
                        Press Loft Affiliate
                    </div>
                    <div class="extensions-squares__description">
                        The Press Loft Affiliate Extension will connect your Magento store to the Press Loft affiliate network and allow Press Loft to track orders
                        completed using affiliate links.
                    </div>
                </div>

                <a href="https://commercemarketplace.adobe.com/pressloft-affiliate.html">
                    <button type="button" class="service-section__button _button _button--arrow">
                        <span class="_button__text"> View on Github </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> View on Github </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
                <meta itemprop="position" content="1" />
            </div>
            <div class="extensions-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <img src="{{media url='wysiwyg/extensions/icon-sales-orders.svg'}}" alt=" Sales&Orders" />
                <div class="extensions-squares__text">
                    <div class="extensions-squares__title">
                        Sales&Orders
                    </div>
                    <div class="extensions-squares__description">
                        Integration Extension for Sales&Orders, a full-suite of features, tools, and services dedicated to helping retailers attract more
                        shoppers and increase sales.
                    </div>
                </div>

                <a href="https://commercemarketplace.adobe.com/partner/ian_weyenberg/">
                    <button type="button" class="service-section__button _button _button--arrow">
                        <span class="_button__text"> View on Github </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> View on Github </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
                <meta itemprop="position" content="1" />
            </div>
        </div>
        <section
            class="form-wide second"
            x-data="{...initForm({'formUniqueId' : 'extensions',
                             'url' : '/perspective_forms/index/gasubmit',
                             'gtmEventName' : 'sent_hire_us_form'
                            }),
                ...formValidation.global(document.getElementById('form_extensions')),
                openForm : false
                }"
        >
            <div class="form-wide__row" x-show="showForm">
                <div class="form-wide__image">
                    <img src="{{view url='Mirasvit_Blog::images/article/gtm/gears.png'}}" alt="Gears illustration" />
                </div>
                <div class="form-wide__content">
                    <h4 class="h4">We know how to do it right</h4>

                    <h6 class="h5">
                        Implementing a Magento PWA can be a complex process with potential pitfalls. But with our expertise in
                        Magento development and PWA integration, we ensure a seamless, error-free experience, enhancing your
                        eCommerce capabilities. Trust us to do it right.
                    </h6>
                    <button
                        class="form-contact__submit footer__button _button _button--white open-form"
                        @click="openForm=true;localStorage.setItem('isAnyFormTouched', true)"
                        x-show="!openForm"
                    >
                        <span class="_button__text">I want to order a service</span>
                        <span class="_button__text-overlay">I want to order a service</span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                    <form
                        id="form_extensions"
                        class="footer__form form-contact contact-form contact-form--orange-bg"
                        :class="{'show' : openForm}"
                        @submit="submitForm($event)"
                    >
                        <div class="form-contact__body">
                            <input
                                type="text"
                                name="first_name"
                                class="form-contact__input"
                                placeholder="Name"
                                required
                                x-on:input="validate($el, false)"
                            />
                            <input
                                type="email"
                                name="email"
                                class="form-contact__input validate-email"
                                placeholder="Email"
                                required
                                x-on:input="validate($el, false)"
                            />
                            <input
                                type="text"
                                name="url"
                                class="form-contact__input"
                                placeholder="Website URL"
                                required
                                x-on:input="validate($el, false)"
                            />
                            <input
                                type="text"
                                name="message"
                                class="form-contact__input"
                                placeholder="How can we help you?"
                                required
                                x-on:input="validate($el, false)"
                            />
                            <input type="hidden" name="type" value="Z2FfcmVxdWVzdA==" />
                        </div>
                        <div class="form-actions">
                            <button type="submit" class="form-contact__submit footer__button _button _button--white contact-submit">
                                <span class="_button__text">Send</span>
                                <span class="_button__text-overlay">Send</span>
                                <span class="_button__overlay _button__overlay--hover"></span>
                                <span class="_button__overlay _button__overlay--active"></span>
                            </button>
                            <button class="footer__button _button close-form" @click="openForm=false" type="button">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="success-message" x-show="showSuccess" :class="{'show' : showSuccess}">
                <img/home/vita/projects/rostilos/files for admin/CMS Pages
                loading="lazy"
                src="{{view url='Mirasvit_Blog::images/article/gtm/rocket.gif'}}"
                alt="Gif with a flying rocket indicating the successful process of sending the form"
                />
                <h5 class="h5">Thank you!</h5>
                <h6 class="h6">We will contact you shortly.</h6>
                <button
                    class="form-contact__submit footer__button _button _button--white success-form"
                    @click="toggleSuccessMessage()"
                >
                    <span class="_button__text">Send another message</span>
                    <span class="_button__text-overlay">Send another message</span>
                    <span class="_button__overlay _button__overlay--hover"></span>
                    <span class="_button__overlay _button__overlay--active"></span>
                </button>
            </div>
        </section>
    </div>
</div>

