<div class="container main-page">
    <!-- BG image (SVG) add to page using CSS pseudo-element :after-->
    <div class="main-page__bg-image"></div>

    <h1 class="_hidden">We are your best Magento Team</h1>

    <div class="main-intro">
        <div class="main-intro__body _container">
            <div class="main-intro__title intro-title">
                <div class="intro-title__top">
                    <div class="intro-title__left _sliding-text">
                        <p class="intro-title__big-letters _sliding-text__line">
                            We are<span class="intro-title__whitespace">&nbsp;</span>
                        </p>
                        <p class="intro-title__big-letters _sliding-text__line">your best</p>
                    </div>
                    <div class="intro-title__right">
                        <p class="intro-title__sub-title">
                            web design <br />project development
                            <br />integration with external systems
                            <br />support and scale
                        </p>
                    </div>
                </div>
                <div class="intro-title__bottom _sliding-text">
                    <span class="intro-title__big-letters _sliding-text__line">
                        <span class="intro-title__big-letters intro-title__big-letters--orange">magento</span>
                        Team
                    </span>
                </div>
            </div>
            <div class="main-intro__digits digits-intro">
                <div class="digits-intro__item">
                    <div class="digits-intro__number">13</div>
                    <div class="digits-intro__text">
                        years <br />of experience
                    </div>
                </div>
                <div class="digits-intro__item">
                    <div class="digits-intro__number">67</div>
                    <div class="digits-intro__text">
                        employees <br />in the team
                    </div>
                </div>
                <div class="digits-intro__item">
                    <div class="digits-intro__number">82</div>
                    <div class="digits-intro__text">
                        successfull <br />projects
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="orange-block">
        <div class="orange-block__container _container _grid-2-col">
            <div class="orange-block__col">
                <div class="_section-label _section-label--white">
                    How we do it
                </div>
            </div>
            <div class="orange-block__col">
                <h3 class="h3 orange-block__title _sliding-text">
                    <span class="_sliding-text__line">Your roadmap</span>
                    <br /><span class="_sliding-text__line">to success</span>
                </h3>
                <div class="vector-absolute-images">
                    <div class="images-card-element">
                        <img loading="lazy" class="Rocet-1 rocket" src="{{media url='wysiwyg/Main/Rocet.png'}}" alt="line" /><img loading="lazy" class="lineV-1 line" src="{{media url='wysiwyg/Main/LineV.png'}}" alt="line" />
                        <div class="success__describe--item">
                            <span class="text">01. Research </span><span class="text">&amp; analysis</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img loading="lazy" class="Rocet-2 rocket" src="{{media url='wysiwyg/Main/Rocet.png'}}" alt="line" /><img loading="lazy" class="lineV-2 line" src="{{media url='wysiwyg/Main/LineV.png'}}" alt="line" />
                        <div class="success__describe--item">
                            <span class="text">02. Planning </span><span class="text">&amp; estimation</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img loading="lazy" class="Rocet-3 rocket" src="{{media url='wysiwyg/Main/Rocet.png'}}" alt="line" /><img loading="lazy" class="lineV-3 line" src="{{media url='wysiwyg/Main/LineV.png'}}" alt="line" />
                        <div class="success__describe--item">
                            <span class="text">03. Designing </span><span class="text">user interfaces</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img loading="lazy" class="Rocet-4 rocket" src="{{media url='wysiwyg/Main/Rocet.png'}}" alt="line" /><img loading="lazy" class="lineV-4 line" src="{{media url='wysiwyg/Main/LineV.png'}}" alt="line" />
                        <div class="success__describe--item">
                            <span class="text">04. Development </span><span class="text">&amp; Coding</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img loading="lazy" class="Rocet-5 rocket" src="{{media url='wysiwyg/Main/Rocet.png'}}" alt="line" /><img loading="lazy" class="lineV-5 line" src="{{media url='wysiwyg/Main/LineV.png'}}" alt="line" />
                        <div class="success__describe--item">
                            <span class="text">05. Validate </span><span class="text">&amp; beta test</span>
                        </div>
                    </div>
                    <div class="images-card-element">
                        <img loading="lazy" class="Rocet-6 rocket" src="{{media url='wysiwyg/Main/Rocet.png'}}" alt="line" /><img loading="lazy" class="lineV-6 line" src="{{media url='wysiwyg/Main/LineV.png'}}" alt="line" />
                        <div class="success__describe--item">
                            <span class="text">06. Deployment </span><span class="text">&amp; Maintenance</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="digital-block _container">
        <div class="digital-block__body _grid-2-col">
            <div class="digital-block__section-label">
                <div class="_section-label">Services</div>
            </div>

            <div class="digital-block__content">
                <div class="digital-block__top">
                    <div class="digital-block__describe">
                        <h3 class="h3 digital-block__title _sliding-text">
                            <span class="_sliding-text__line">All Digital Services</span>
                            <br />
                            <span class="_sliding-text__line">Under One Roof</span>
                        </h3>
                        <h5 class="h5 digital-block__sub-title _text-align-right">
                            We have a wealth of experience working with corporate and personal clients. Many of those clients have worked with us for more than 5 years.
                        </h5>
                    </div>
                    <div class="digital-block__image">
                        <img loading="lazy" class="img loading=" src="{{media url='wysiwyg/Main/Cube.svg'}}" alt="Cube-service " />
                    </div>
                </div>

                <div class="digital-block__bot">
                    <div class="digital-block__squares digital-squares digital-squares--desk">
                        <div class="digital-squares__row">
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Web Design</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento Development</h4>
                                </div>
                            </div>
                            <div class="digital-squares__empty"></div>
                            <div class="digital-squares__empty"></div>
                        </div>

                        <div class="digital-squares__row">
                            <div class="digital-squares__empty"></div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento 2 Migration</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento <br /> PWA</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento <br /> Support</h4>
                                </div>
                            </div>
                        </div>

                        <div class="digital-squares__row">
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Server & Magento <br /> Optimization</h4>
                                </div>
                            </div>
                            <div class="digital-squares__empty"></div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento <br /> Security Audit</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item digital-squares__item--no-border--centered">
                                <a href="{{store url='services'}}" class="digital-block__link _link-arrow">Discover more</a>
                            </div>
                        </div>
                    </div>

                    <div class="digital-block__squares digital-squares digital-squares--mob">
                        <div class="digital-squares__col">
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento Development</h4>
                                </div>
                            </div>

                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento PWA</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Server & Magento Optimization</h4>
                                </div>
                            </div>
                        </div>
                        <div class="digital-squares__col">
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Web Design</h4>
                                </div>
                            </div>

                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento 2 Migration</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento Support</h4>
                                </div>
                            </div>
                            <div class="digital-squares__item">
                                <div class="digital-squares__content">
                                    <h4 class="h4">Magento Security Audit</h4>
                                    <!--  -->
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="digital-block__show-more">
                    <a class="digital-block__link _link-arrow" href="{{store url='services'}}">
                        Discover more
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="integration _container">
        <div class="integration__body _grid-2-col">
            <div class="integration__section-label">
                <div class="_section-label">Integration</div>
            </div>
            <div class="integration__body">
                <div class="integration__top">
                    <div class="integration__image">
                        <img loading="lazy" class="describe__image--item" src="{{media url='wysiwyg/Main/integration.svg'}}" alt="integration " />
                        <h5 class="h5 integration__text integration__text--mobile _text-align-right">
                            Integrate your Magento website with any backend
                            system or external software to automate your work
                            processes and execute your business strategy more
                            efficiently.
                        </h5>
                    </div>
                    <div class="integration__content">
                        <h3 class="h3 integration__title _sliding-text">
                            <span class="_sliding-text__line">Integrate with </span>
                            <br /><span class="_sliding-text__line">any ecommerce</span>
                            <br /><span class="_sliding-text__line">services</span>
                        </h3>
                        <h5 class="h5 integration__text _text-align-right">
                            Integrate your Magento website with any backend system or external
                            software to automate your work processes and execute your business
                            strategy more efficiently.
                        </h5>
                    </div>
                </div>
                <div class="integration__bot">
                    <div class="integration__cards integration-cards">
                        <!-- Headless CMS -->
                        <div class="integration-cards__item">

                            <input checked="true" name="integration-cards" type="radio" id="integration-cards__arrow_1" class="integration-cards__arrow" />
                            <label for="integration-cards__arrow_1">
                                <h4 class="h4 integration-cards__title">
                                    <span>Headless CMS</span>
                                </h4>
                            </label>
                            <div class="integration-cards__images integrations-logo">
                                <div class="integrations-logo__row">
                                    <img loading="lazy" height="27px" width="113px" src="{{media url='wysiwyg/Main/logos/headless/gatsby-inc-vector-logo_2.svg'}}" alt="hover" />
                                    <img loading="lazy" height="34px" width="59px" src="{{media url='wysiwyg/Main/logos/headless/PWA_logo_3.svg'}}" alt="hover" />
                                    <img loading="lazy" height="41px" width="104px" src="{{media url='wysiwyg/Main/logos/headless/Logo.f339de60_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/headless/storyblok-logo.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/headless/image_156.png'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/headless/vsf-full_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/headless/image_157.png'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/headless/angular_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/headless/logo-falcon-platform-inverted.31aaadf3_2.svg'}}" alt="hover" />

                                </div>
                            </div>
                        </div>
                        <!-- Payments -->
                        <div class="integration-cards__item">
                            <input name="integration-cards" type="radio" id="integration-cards__arrow_2" class="integration-cards__arrow" />
                            <label for="integration-cards__arrow_2">
                                <h4 class="h4 integration-cards__title">
                                    <span>Payments</span>
                                </h4>

                            </label>
                            <div class="integration-cards__images integrations-logo">
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/PayPal_logo.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Google_Pay__GPay__Logo__2018-2020_.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Apple_Pay_logo.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/skrillfuture-logo_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Afterpay-Logo.wine_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/BlueSnap-logo_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Klarna_Logo_black_2.svg'}}" alt="hover" />

                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Alipay_logo__2020_2.svg'}}" alt="hover" />

                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/eway-logo-1_2.svg'}}" alt="hover" />

                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Adyen_Corporate_Logo_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Authorize.net_Logo_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/image_166.png'}}" alt="hover" />

                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Amazon_Pay_logo_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/mollie-vector-logo.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Stripe_Logo__revised_2016_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/208457_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/Opayo-logo_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/payments/image_167.png'}}" alt="hover" />
                                </div>
                            </div>
                        </div>
                        <!-- Third-party services -->
                        <div class="integration-cards__item">
                            <input name="integration-cards" type="radio" id="integration-cards__arrow_3" class="integration-cards__arrow" />
                            <label for="integration-cards__arrow_3">
                                <h4 class="h4 integration-cards__title">
                                    <span>Third party services</span>
                                </h4>
                            </label>

                            <div class="integration-cards__images integrations-logo">
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/EBay_logo_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/DPD_logo__2015_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/Etsy_logo_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/image_160.png'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/dhl-3.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/avalara_2.svg'}}" alt="hover" />

                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/RabbitMQ_logo_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/image_157.png'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/image_159.png'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/third-party/shq-logo-hz-3c-05959a274f3d19cc5524b2aa0d31ca6130905740c1ff0fc095289259bdbd2979_2.svg'}}" alt="hover" />
                                </div>
                            </div>
                        </div>
                        <!-- Search eng -->
                        <div class="integration-cards__item">
                            <input name="integration-cards" type="radio" id="integration-cards__arrow_4" class="integration-cards__arrow" />
                            <label for="integration-cards__arrow_4">
                                <h4 class="h4 integration-cards__title">
                                    <span>Search eng</span>
                                </h4>
                            </label>

                            <div class="integration-cards__images integrations-logo">
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/search-eng/Logo_1.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/search-eng/Elasticsearch_logo_1.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/search-eng/Algolia-logo_1.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/search-eng/image_154.png'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/search-eng/Amazon_Web_Services_Logo_1.svg'}}" alt="hover" />
                                </div>
                            </div>
                        </div>
                        <!-- Cloud solutions -->
                        <div class="integration-cards__item">
                            <input name="integration-cards" type="radio" id="integration-cards__arrow_5" class="integration-cards__arrow" />
                            <label for="integration-cards__arrow_5">
                                <h4 class="h4 integration-cards__title">
                                    <span>Cloud solutions</span>
                                </h4>
                            </label>

                            <div class="integration-cards__images integrations-logo">
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/image_166.png'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/Microsoft_Azure_Logo_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/digitalocean-2_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/magento-logo_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/image_167.png'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/nexcess-net-llc-logo-vector_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/Element_1_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/amazon-cloudfront-logo_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/Kubernetes_logo_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/cloud-solutions/Group.svg'}}" alt="hover" />
                                </div>
                            </div>
                        </div>
                        <!-- CRM, ERP, PIM -->
                        <div class="integration-cards__item">
                            <input name="integration-cards" type="radio" id="integration-cards__arrow_6" class="integration-cards__arrow" />
                            <label for="integration-cards__arrow_6">
                                <h4 class="h4 integration-cards__title">
                                    <span>CRM, ERP, PIM</span>
                                </h4>
                            </label>

                            <div class="integration-cards__images integrations-logo">
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/crm-erp-pim/Group_576.png'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/crm-erp-pim/image_166.png'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/crm-erp-pim/akeneo-logo-vector_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/crm-erp-pim/image_167.png'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/crm-erp-pim/Pimcore-logo-5_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/crm-erp-pim/image_169.png'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/crm-erp-pim/zoho-seeklogo.com_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/crm-erp-pim/image_168.png'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/crm-erp-pim/comarch-vector-logo_2.svg'}}" alt="hover" />
                                </div>
                            </div>
                        </div>
                        <!-- Senders -->
                        <div class="integration-cards__item">
                            <input name="integration-cards" type="radio" id="integration-cards__arrow_7" class="integration-cards__arrow" />
                            <label for="integration-cards__arrow_7">
                                <h4 class="h4 integration-cards__title">
                                    <span>Senders</span>
                                </h4>
                            </label>

                            <div class="integration-cards__images integrations-logo">
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/senders/klaviyo-vector-logo_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/senders/mailchimp-vector-logo_2.svg'}}" alt="hover" />
                                </div>
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/senders/sendgrid-ar21_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/senders/mailgun-ar21_2.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/senders/Rakuten_Global_Brand_Logo_2.svg'}}" alt="hover" />
                                </div>
                            </div>
                        </div>
                        <!-- Reviews -->
                        <div class="integration-cards__item">
                            <input name="integration-cards" type="radio" id="integration-cards__arrow_8" class="integration-cards__arrow" />
                            <label for="integration-cards__arrow_8">
                                <h4 class="h4 integration-cards__title">
                                    <span>Reviews</span>
                                </h4>
                            </label>

                            <div class="integration-cards__images integrations-logo">
                                <div class="integrations-logo__row">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/reviews/Yotpo-logo_1.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/reviews/reviews-io-vector-logo_1.svg'}}" alt="hover" />
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/logos/reviews/feefo-vector-logo_1.svg'}}" alt="hover" />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="company">
        <div class="company__bg-lines"></div>
        <div class="company__container _container">
            <div class="company__body _grid-3-col">
                <div class="company__section-label _section-label">Company</div>
                <div class="company__col">
                    <h3 class="h3 company__title _sliding-text">
                        <span class="_sliding-text__line">Who we are</span>
                    </h3>
                    <h5 class="h5 company__text _text-align-right">
                        With more than a decade of experience, Perspective has become a leader in digital experiences.<br />
                        Clients worldwide entrust us with their website design, development, and management.
                    </h5>

                    <div class="company__squares squares-company squares-company--mobile">
                        <div class="squares-company__square">
                            <div class="squares-company__number">10</div>
                            <h5 class="h5 squares-company__text">
                                front-end developers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">32</div>
                            <h5 class="h5 squares-company__text">
                                back-end developers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">12</div>
                            <h5 class="h5 squares-company__text">
                                QA engineers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">4</div>
                            <h5 class="h5 squares-company__text">
                                DevOps & SysOps
                            </h5>
                        </div>
                    </div>
                    <h5 class="h5 company__text _text-align-right">
                        We are the Magento‑focused web‑development company named Perspective Studio, with HQ in Kyiv, Ukraine, with more than 60 employees.
                        <br />
                        Most are strong middle and senior developers with 5+ years of experience in Magento.
                    </h5>
                    <div class="company__image">
                        <img loading="lazy" src="{{media url='wysiwyg/Main/who-we.png'}}" alt="who-we-are" />
                    </div>
                </div>
                <div class="company__col">
                    <div class="company__squares squares-company squares-company--desktop">
                        <div class="squares-company__square">
                            <div class="squares-company__number">10</div>
                            <h5 class="h5 squares-company__text">
                                front-end developers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">32</div>
                            <h5 class="h5 squares-company__text">
                                back-end developers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">12</div>
                            <h5 class="h5 squares-company__text">
                                QA engineers
                            </h5>
                        </div>

                        <div class="squares-company__square">
                            <div class="squares-company__number">4</div>
                            <h5 class="h5 squares-company__text">
                                DevOps & SysOps
                            </h5>
                        </div>
                    </div>
                    <h5 class="h5 company__text _text-align-right">
                        Our philosophy is built on people who love creating,
                        learning and growing together. Our studio of more than
                        60 people who form a team with ties that transcend the
                        workplace.
                    </h5>

                    <div class="company__button-box">
                        <a href="{{store url='company'}}">
                            <button class="company__button _button _button--white _button--arrow">
                                <span class="_button__text">More about us</span>
                                <span class="_button__text-overlay _button__text-overlay--black">More about us</span>
                                <span class="_button__overlay _button__overlay--hover"></span>
                                <span class="_button__overlay _button__overlay--active"></span>
                            </button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="work">
        <div class="work__container _container">
            <div class="work__body _grid-2-col">
                <div class="work__section-label _section-label">Work</div>
                <div class="work__content">
                    <h3 class="h3 work__title _sliding-text">
                        <span class="_sliding-text__line">We build timeless</span>
                        <br /><span class="_sliding-text__line">experiences</span>
                    </h3>
                    <div class="work__gallery gallery" data-mage-init='{"slickMainPage": {}}'>
                        <div class="gallery__container">
                            <div class="gallery__content">
                                <div class="gallery__col">
                                    <div class="gallery__text _text-align-right">
                                        We develop, design and delivers websites
                                        that drive results. Our work never
                                        brags, but it sure loves to speak for
                                        itself.
                                    </div>
                                    <div class="gallery__slide gallery-slide">
                                        <div class="gallery-slide__image">
                                            <img loading="lazy" src="{{media url='wysiwyg/Main/tefal.png'}}" alt="tefal" />
                                        </div>
                                        <div class="gallery-slide__content">
                                            <span class="gallery-slide__title">
                                                Tefal
                                            </span>
                                            <p class="gallery-slide__text">
                                                Design, development,
                                                integrations,support
                                            </p>
                                        </div>
                                    </div>
                                    <div class="gallery__slide gallery-slide">
                                        <div class="gallery-slide__image">
                                            <img loading="lazy" src="{{media url='wysiwyg/Main/berg.png'}}" alt="berg " />
                                        </div>
                                        <div class="gallery-slide__content">
                                            <span class="gallery-slide__title">
                                                Dr.Berg
                                            </span>
                                            <p class="gallery-slide__text">
                                                Development, integrations,
                                                support
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="gallery__col gallery__col--reverse">
                                    <a class="gallery__show-more _link-arrow" href="{{store url='work'}}">
                                        See all work
                                    </a>
                                    <div class="gallery__slide gallery-slide">
                                        <div class="gallery-slide__image">
                                            <img loading="lazy" src="{{media url='wysiwyg/Main/ortlieb.png'}}" alt="ortrieb " />
                                        </div>
                                        <div class="gallery-slide__content">
                                            <span class="gallery-slide__title">
                                                Ortrieb
                                            </span>
                                            <p class="gallery-slide__text">
                                                Development, integrations,
                                                support
                                            </p>
                                        </div>
                                    </div>
                                    <div class="gallery__slide gallery-slide">
                                        <div class="gallery-slide__image">
                                            <img loading="lazy" src="{{media url='wysiwyg/Main/vodofon.png'}}" alt="vodofon " />
                                        </div>
                                        <div class="gallery-slide__content">
                                            <span class="gallery-slide__title">
                                                Vodafon
                                            </span>
                                            <p class="gallery-slide__text">
                                                Development, integrations,
                                                support
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div class="gallery__col--mobile"></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="trusted">
        <div class="trusted__container _container">
            <div class="trusted__body _grid-2-col">
                <div class="trusted__section-label _section-label">
                    Our clients
                </div>
                <div class="trusted__content">
                    <div class="trusted__header">
                        <h3 class="h3 trusted__title _sliding-text">
                            <span class="_sliding-text__line">We are trusted</span>
                        </h3>
                        <h5 class="h5 trusted__sub-title _text-align-right">
                            We make Magento work for our clients with perfect codes, engaging
                            interactions, thoughtful integrations and a commitment to ongoing
                            support.
                        </h5>
                    </div>

                    <div class="trusted__table trusted-table">
                        <div class="trusted-table__item trusted-table__item--empty"></div>
                        <div class="trusted-table__item trusted-table__item--empty"></div>
                        <div class="trusted-table__item trusted-table__item--empty"></div>
                        <div class="trusted-table__item trusted-table__item--krups">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/krups.png'}}" alt="krups" />
                            </div>
                        </div>

                        <div class="trusted-table__item trusted-table__item--vod">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/Vodafone.png'}}" alt="vodofon " />
                            </div>
                        </div>
                        <div class="trusted-table__item trusted-table__item--tef">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/tefal.png'}}" alt="tefal " />
                            </div>
                        </div>
                        <div class="trusted-table__item trusted-table__item--tmm">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/tmm.png'}}" alt="tmm " />
                            </div>
                        </div>
                        <div class="trusted-table__item trusted-table__item--chic">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/chicco.png'}}" alt="chicco " />
                            </div>
                        </div>

                        <div class="trusted-table__item trusted-table__item--dr">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/DrBerg.png'}}" alt="berg " />
                            </div>
                        </div>
                        <div class="trusted-table__item trusted-table__item--2-col trusted-table__item--aphid">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/AphidDigital.png'}}" alt="degital " />
                            </div>
                        </div>
                        <div class="trusted-table__item trusted-table__item--ortl">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/Ortlieb_.png'}}" alt="ortlieb " />
                            </div>
                        </div>

                        <div class="trusted-table__item trusted-table__item--empty"></div>
                        <div class="trusted-table__item trusted-table__item--sea">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/Seaguar.png'}}" alt="seguar " />
                            </div>
                        </div>
                        <div class="trusted-table__item trusted-table__item--good">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/Goodvine.png'}}" alt="goodvine " />
                            </div>
                        </div>
                        <div class="trusted-table__item trusted-table__item--empty"></div>

                        <div class="trusted-table__item trusted-table__item--dfg">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/Degrau.png'}}" alt="degrau " />
                            </div>
                        </div>
                        <div class="trusted-table__item trusted-table__item--hum">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/HUMco.png'}}" alt="HUMco " />
                            </div>
                        </div>
                        <div class="trusted-table__item trusted-table__item--2-col trusted-table__item--beach">
                            <div class="trusted-table__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/logo/Beachcomer.png'}}" alt="beach " />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="comments" data-mage-init='{"slickComments": {}}'>
        <div class="comments__container _container _grid-2-col">
            <div class="comments__section-label _section-label">
                Testimonials
            </div>
            <div class="comments__body">
                <div class="comments__header">
                    <h3 class="h3 comments__title _sliding-text">
                        <span class="_sliding-text__line">What our clients</span>
                        <br /><span class="_sliding-text__line">say about us</span>
                    </h3>
                    <h5 class="h5 comments__sub-title _text-align-right">
                        We have a wealth of experience working with corporate and personal clients. Many of those clients have worked with us for more than 5 years.
                    </h5>
                </div>

                <div class="comments__content">
                    <ul class="comments__list">
                        <!-- Vodafone -->
                        <div class="comments__item comment">
                            <div class="comment__header">
                                <div class="comment__icon">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/message/Group.png'}}" alt="C " />
                                </div>
                                <div class="comment__rate">
                                    <div class="comment__rate-number">
                                        <span>5.0</span>
                                    </div>
                                    <div class="comment__stars">
                                        <span class="stars-icons">
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                        </span>
                                        <span class="stars-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="comment__body">
                                <div class="comment__author comment-author">
                                    <div class="comment-author__name">
                                        Vitaly Zadorin
                                    </div>
                                    <div class="comment-author__post">
                                        Product Owner, Vodafone Ukraine
                                    </div>
                                </div>

                                <div class="comment__text">
                                    <p>
                                        The project launched just in time for a big shopping event and the company saw firsthand how well it worked under high traffic. The team used a variety of tools for development and communication with the company.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!-- E-Shop -->
                        <div class="comments__item comment">
                            <div class="comment__header">
                                <div class="comment__icon">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/message/Group.png'}}" alt="C " />
                                </div>
                                <div class="comment__rate">
                                    <div class="comment__rate-number">
                                        <span>5.0</span>
                                    </div>
                                    <div class="comment__stars">
                                        <span class="stars-icons">
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                        </span>
                                        <span class="stars-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="comment__body">
                                <div class="comment__author comment-author">
                                    <div class="comment-author__name">
                                        Kluka Anna
                                    </div>
                                    <div class="comment-author__post">
                                        E-Shop Manager, Groupe SEB Ukraine
                                    </div>
                                </div>

                                <div class="comment__text">
                                    <p>
                                        Perspective delivered the final output exactly how the client requested, which eventually led to the achievement of the company's goals. The team also thoroughly followed the given timeline.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!-- Aphid -->
                        <div class="comments__item comment">
                            <div class="comment__header">
                                <div class="comment__icon">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/message/Group.png'}}" alt="C " />
                                </div>
                                <div class="comment__rate">
                                    <div class="comment__rate-number">
                                        <span>5.0</span>
                                    </div>
                                    <div class="comment__stars">
                                        <span class="stars-icons">
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                        </span>
                                        <span class="stars-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="comment__body">
                                <div class="comment__author comment-author">
                                    <div class="comment-author__name">
                                        Shane Doerksen
                                    </div>
                                    <div class="comment-author__post">
                                        Solution Architect, Aphid Consulting
                                    </div>
                                </div>

                                <div class="comment__text">
                                    <p>
                                        Perspective Studio has delivered an exceptional project on time and within the budget. The team is reliable, responsive, friendly, professional, and fluent in English.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <!-- Book -->
                        <div class="comments__item comment">
                            <div class="comment__header">
                                <div class="comment__icon">
                                    <img loading="lazy" src="{{media url='wysiwyg/Main/message/Group.png'}}" alt="C " />
                                </div>
                                <div class="comment__rate">
                                    <div class="comment__rate-number">
                                        <span>5.0</span>
                                    </div>
                                    <div class="comment__stars">
                                        <span class="stars-icons">
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                            <span class="stars-icon"></span>
                                        </span>
                                        <span class="stars-bar"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="comment__body">
                                <div class="comment__author comment-author">
                                    <div class="comment-author__name">
                                        Stuart Hutchinson
                                    </div>
                                    <div class="comment-author__post">
                                        Basement Books
                                    </div>
                                </div>

                                <div class="comment__text">
                                    <p>
                                        Perspective successfully finished the client's platform, and they were able to accomplish all of their tasks. They had exceptional Magento skills, and they were able to solve all of the project's issues. The team was also commended for their organized and meticulous approach.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </ul>

                    <div class="comments__controls">
                        <div class="comments__arrow comments__arrow--prev"></div>
                        <div class="comments__arrow comments__arrow--next"></div>
                    </div>
                    <div class="comments__reviews">
                        <span></span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="main-certification">
        <div class="main-certification__container _container _grid-3-col">
            <div class="main-certification__section-label _section-label">
                Certification
            </div>
            <div class="main-certification__col">
                <h3 class="h3 comments__title _sliding-text">
                    <span class="_sliding-text__line">Great projects</span> <br /><span class="_sliding-text__line">requires great</span>
                    <br /><span class="_sliding-text__line">engineers</span>
                </h3>
                <p class="main-certification__text _text-align-right">
                    We know how important adherence is. <br />
                    That’s why some of the current certifications include
                    the following:
                </p>
                <div class="main-certification__adobe-achievments adobe-achievments">
                    <ul class="adobe-achievments__list">
                        <li class="adobe-achievments__item adobe-achievments__item--image-full">
                            <img loading="lazy" src="{{media url='wysiwyg/Main/e2f1a9f-890.png'}}" alt="" />
                        </li>

                        <li class="adobe-achievments__item">
                            <div class="adobe-achievments__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/Adobe_Certified_Professional_Experience_Cloud_products_Digital_Badge.png'}}" alt="" />
                            </div>
                            <div class="adobe-achievments__body">
                                <div class="adobe-achievments__name">
                                    Adobe Certified Professional
                                </div>
                                <div class="adobe-achievments__text">
                                    Back-end Developer
                                </div>
                            </div>
                        </li>

                        <li class="adobe-achievments__item">
                            <div class="adobe-achievments__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/Adobe_Certified_Expert.png'}}" alt="" />
                            </div>
                            <div class="adobe-achievments__body">
                                <div class="adobe-achievments__name">
                                    Adobe Certified Expert
                                </div>
                                <div class="adobe-achievments__text">
                                    Front-end Developer<br />
                                    Back-end Developer<br />
                                    Business Practitioner
                                </div>
                            </div>
                        </li>

                        <li class="adobe-achievments__item">
                            <div class="adobe-achievments__image">
                                <img loading="lazy" src="{{media url='wysiwyg/Main/Adobe_Certified_Master_Experience_Cloud_products_Digital_Badge.png'}}" alt="" />
                            </div>
                            <div class="adobe-achievments__body">
                                <div class="adobe-achievments__name">
                                    Adobe Certified Master
                                </div>
                                <div class="adobe-achievments__text">
                                    Architect
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="main-certification__col">
                <div class="main-certification__text--open-sans">
                    <p class="_text-align-right">
                        Also, we already have 8 certified developers and solution specialists with 13 certificates for M1 and M2.
                    </p>
                </div>
                <div class="main-certification__magento-achievments magento-achievments">
                    <div class="magento-achievments__all">
                        <img loading="lazy" src="{{media url='wysiwyg/Group-525.png'}}" alt="all" />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="badges">
        <div class="badges__container _container _grid-2-col">
            <div class="badges__section-label _section-label">
                Badges
            </div>
            <div class="badges__col">
                <div class="flex badges__list badges-list">
                    <div class="badges-list__item">
                        <a href="https://clutch.co/profile/perspective-1">
                            <img class="badges-list__image" width="166" height="180" src="{{media url='wysiwyg/Main/badges/clutch.png'}}" alt="clutch">
                        </a>
                    </div>
                    <div class="badges-list__item">
                        <a href="https://techreviewer.co/companies/perspective-team">
                            <img class="badges-list__image" width="137" height="180" src="{{media url='wysiwyg/Main/badges/TopeCom.svg'}}" alt="TopeCom">
                        </a>
                    </div>
                    <div class="badges-list__item">
                        <a href="https://www.goodfirms.co/company/perspective-team">
                            <img class="badges-list__image" width="210" height="180" src="{{media url='wysiwyg/Main/badges/GoodFirms.svg'}}" alt="GoodFirms">
                        </a>
                    </div>
                    <div class="badges-list__item">
                        <a href="https://www.designrush.com/agency/profile/perspective-team">
                            <img class="badges-list__image" width="128" height="180" src="{{media url='wysiwyg/Main/badges/designrush.png'}}" alt="Designrush">
                        </a>
                    </div>
                    <!-- <div class="badges-list__item">
                        <a href=""></a>
                        <img class="badges-list__image" width="180" height="180" src="{{media url='wysiwyg/Main/badges/TopDev.png'}}" alt="TopDev">
                    </div> -->
                </div>
            </div>
        </div>
    </div>
</div>