<div class="services-page" data-mage-init='{"servicepage":{}}'>
    <div class="services-page__container _container">
        <div class="service-page__top _grid-3-col">
            <h1 class="h2 services-page__title _sliding-text">
                <span class="_sliding-text__line">We are a team <br /> </span>
                <span class="_sliding-text__line">of international experts</span>
                <span class="_sliding-text__line">
          united by a
          <span class="services-page__title services-page__title--orange">single goal</span>
        </span>
            </h1>
            <h2 class="h4 services-page__sub-title">
                We specialize in creating eCommerce websites that bring new customers in balance with your brand. Our websites
                are future-proof, with a solid backend and an easy-to-use content management system. We maintain, update, and
                support ongoing strategic recommendations from the minute you go live.
            </h2>
        </div>

        <div
                class="services-page__squares services-squares"
                data-mage-init='{"slickServicePage":{}}'
                itemscope
                itemtype="https://schema.org/BreadcrumbList"
        >
            <div class="services-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <a itemprop="item" class="_scrollTo" href="#services-design-section" data-order-mob="1" data-order-desktop="1">
                    <p class="service-squares__text" itemprop="name">
                        Web Design <br />
                        for Magento
                    </p>
                </a>
                <meta itemprop="position" content="1" />
            </div>
            <div class="services-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <a
                        itemprop="item"
                        class="_scrollTo"
                        href="#services-migration-section"
                        data-order-mob="3"
                        data-order-desktop="2"
                >
                    <p class="service-squares__text" itemprop="name">Migration to Magento 2</p>
                </a>
                <meta itemprop="position" content="2" />
            </div>
            <div class="services-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <a itemprop="item" class="_scrollTo" href="#services-pwa-section" data-order-mob="4" data-order-desktop="3">
                    <p class="service-squares__text" itemprop="name">
                        Magento <br />
                        PWA
                    </p>
                </a>
                <meta itemprop="position" content="3" />
            </div>
            <div class="services-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <a
                        itemprop="item"
                        class="_scrollTo"
                        href="#services-optimization-section"
                        data-order-mob="7"
                        data-order-desktop="4"
                >
                    <p class="service-squares__text" itemprop="name">
                        Server & Magento <br />
                        Optimization
                    </p>
                </a>
                <meta itemprop="position" content="4" />
            </div>

            <div class="services-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <a
                        itemprop="item"
                        class="_scrollTo"
                        href="#services-development-section"
                        data-order-mob="2"
                        data-order-desktop="5"
                >
                    <p class="service-squares__text" itemprop="name">Magento Development</p>
                </a>
                <meta itemprop="position" content="5" />
            </div>
            <div class="services-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <a
                        itemprop="item"
                        class="_scrollTo"
                        href="#services-security-section"
                        data-order-mob="5"
                        data-order-desktop="6"
                >
                    <p class="service-squares__text" itemprop="name">Magento Security Audit</p>
                </a>
                <meta itemprop="position" content="6" />
            </div>
            <div class="services-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <a itemprop="item" class="_scrollTo" href="#services-support-section" data-order-mob="6" data-order-desktop="7">
                    <p class="service-squares__text" itemprop="name">
                        Magento <br />
                        Support
                    </p>
                </a>
                <meta itemprop="position" content="7" />
            </div>
            <div class="services-squares__square" itemprop="itemListElement" itemscope itemtype="https://schema.org/ListItem">
                <a
                        itemprop="item"
                        class="_scrollTo"
                        href="#services-ga4-section"
                        data-order-mob="8"
                        data-order-desktop="8"
                        itemid="{{store url='services/implementation-google-analytics-4-on-magento-2-with-gtm'}}"
                >
                    <p class="service-squares__text" itemprop="name">Implementation<br />Google Analytics 4</p>
                </a>
                <meta itemprop="position" content="8" />
            </div>
        </div>

        <section
                id="services-design-section"
                class="services-page__service-section service-section"
                itemscope
                itemtype="https://schema.org/Product"
        >
            <div class="service-section__body _grid-3-col">
                <div class="service-section__label _section-label" itemprop="keywords">Design</div>
                <div class="service-section__content">
                    <h3 class="h3 service-section__title" itemprop="name">Web Design</h3>
                    <div itemprop="description">
                        <p class="service-section__text">
                            The full cycle of services to create and launch a website from scratch or redesign a live website along
                            with the modern trends and requirements.
                        </p>
                        <p class="service-section__text service-section__text--second-line">
                            We will help you take your online store to the next level with our eCommerce design services. Contact us
                            to learn more about how a good user experience and interface impact your online sales.
                        </p>
                    </div>
                    <a href="{{store url='services/comprehensive-web-design'}}">
                        <button type="button" class="service-section__button _button _button--arrow">
                            <span class="_button__text"> Discover more </span>
                            <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                            <span class="_button__overlay _button__overlay--hover"></span>
                            <span class="_button__overlay _button__overlay--active"></span>
                        </button>
                    </a>
                </div>
                <div class="service-section__image">
                    <img
                            loading="lazy"
                            src="{{media url='wysiwyg/Service/Web_design.svg'}}"
                            alt="devolope-image"
                            itemprop="logo"
                    />
                </div>
                <a
                        class="service-section__mobile"
                        href="{{store url='services/comprehensive-web-design'}}"
                >
                    <button type="button" class="service-section__mobile-button _button _button--arrow">
                        <span class="_button__text"> Discover more </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
            </div>
        </section>

        <section
                id="services-development-section"
                class="services-page__service-section service-section"
                itemscope
                itemtype="https://schema.org/Product"
        >
            <div class="service-section__body _grid-3-col">
                <div class="service-section__label _section-label" itemprop="keywords">Development</div>
                <div class="service-section__image">
                    <img
                            loading="lazy"
                            src="{{media url='wysiwyg/Service/Development.svg'}}"
                            alt="design-image "
                            itemprop="logo"
                    />
                </div>
                <div class="service-section__content">
                    <h3 class="h3 service-section__title" itemprop="name">Magento Development</h3>
                    <div itemprop="description">
                        <p class="service-section__text">
                            Magento is a complex platform and requires the right people to maintain it for it to be stable and
                            flexible in the long run. We are here for that.
                        </p>
                        <p class="service-section__text service-section__text--second-line">
                            Our Magento-certified developers are trained to develop Magento stores with a long-term view of
                            functionality and maintainability in mind.
                        </p>
                    </div>
                    <a href="{{store url='services/magento-development'}}">
                        <button type="button" class="service-section__button _button _button--arrow">
                            <span class="_button__text"> Discover more </span>
                            <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                            <span class="_button__overlay _button__overlay--hover"></span>
                            <span class="_button__overlay _button__overlay--active"></span>
                        </button>
                    </a>
                </div>
                <a
                        class="service-section__mobile"
                        href="{{store url='services/magento-development'}}"
                >
                    <button type="button" class="service-section__mobile-button _button _button--arrow">
                        <span class="_button__text"> Discover more </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
            </div>
        </section>

        <section
                id="services-migration-section"
                class="services-page__service-section service-section"
                itemscope
                itemtype="https://schema.org/Product"
        >
            <div class="service-section__body _grid-3-col">
                <div class="service-section__label _section-label" itemprop="keywords">Migration</div>
                <div class="service-section__content">
                    <h3 class="h3 service-section__title" itemprop="name">
                        Migration to <br />
                        Magento 2
                    </h3>
                    <p class="service-section__text" itemprop="description">
                        Some merchants perceive the Magento 1 to Magento 2 migration process as intimidating, resulting in their
                        postponing the procedure indefinitely. After years of using Magento 1, many grew attached to the familiar
                        features and demonstrated the platform's robustness.
                    </p>
                    <a href="{{store url='services/migration-to-magento-2'}}">
                        <button type="button" class="service-section__button _button _button--arrow">
                            <span class="_button__text"> Discover more </span>
                            <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                            <span class="_button__overlay _button__overlay--hover"></span>
                            <span class="_button__overlay _button__overlay--active"></span>
                        </button>
                    </a>
                </div>
                <div class="service-section__image">
                    <img
                            loading="lazy"
                            src="{{media url='wysiwyg/Service/migration.svg'}}"
                            alt="migration-image "
                            itemprop="logo"
                    />
                </div>
                <a
                        class="service-section__mobile"
                        href="{{store url='services/migration-to-magento-2'}}"
                >
                    <button type="button" class="service-section__mobile-button _button _button--arrow">
                        <span class="_button__text"> Discover more </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
            </div>
        </section>

        <section
                id="services-pwa-section"
                class="services-page__service-section service-section"
                itemscope
                itemtype="https://schema.org/Product"
        >
            <div class="service-section__body _grid-3-col">
                <div class="service-section__label _section-label" itemprop="keywords">PWA</div>
                <div class="service-section__image">
                    <img loading="lazy" src="{{media url='wysiwyg/Service/pwa.svg'}}" alt="migration-image " itemprop="logo" />
                </div>
                <div class="service-section__content">
                    <h3 class="h3 service-section__title" itemprop="name">Magento PWA</h3>
                    <p class="service-section__text" itemprop="description">
                        Empower your Magento by using Progressive Web Apps, thus reaching lightning-fast loading times, improved
                        experience on mobile, and much more. Our extensive experience building Magento PWA stores will ensure your
                        headless eCommerce store is ahead of the competition.
                    </p>
                    <a href="{{store url='services/magento-pwa'}}">
                        <button type="button" class="service-section__button _button _button--arrow">
                            <span class="_button__text"> Discover more </span>
                            <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                            <span class="_button__overlay _button__overlay--hover"></span>
                            <span class="_button__overlay _button__overlay--active"></span>
                        </button>
                    </a>
                </div>
                <a
                        class="service-section__mobile"
                        href="/services/magento-pwa"
                >
                    <button type="button" class="service-section__mobile-button _button _button--arrow">
                        <span class="_button__text"> Discover more </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
            </div>
        </section>

        <section
                id="services-security-section"
                class="services-page__service-section service-section"
                itemscope
                itemtype="https://schema.org/Product"
        >
            <div class="service-section__body _grid-3-col">
                <div class="service-section__label service-section__label--wide _section-label" itemprop="keywords">
                    Security audit
                </div>
                <div class="service-section__content">
                    <h3 class="h3 service-section__title" itemprop="name">
                        Magento <br />
                        Security Audit
                    </h3>
                    <p class="service-section__text" itemprop="description">
                        №1 eCommerce priority covered: be 100% sure the customers’ payment & private information is safe. We will
                        make sure all security flaws won’t be a threat to your store.
                    </p>
                    <ul class="service-section__list">
                        <li>Magento patches review</li>
                        <li>Website malware & security checks</li>
                        <li>Magento code audit</li>
                    </ul>
                    <a href="{{store url='services/magento-security-audit'}}">
                        <button type="button" class="service-section__button _button _button--arrow">
                            <span class="_button__text"> Discover more </span>
                            <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                            <span class="_button__overlay _button__overlay--hover"></span>
                            <span class="_button__overlay _button__overlay--active"></span>
                        </button>
                    </a>
                </div>
                <div class="service-section__image">
                    <img
                            loading="lazy"
                            src="{{media url='wysiwyg/Service/851_Converted_1.svg'}}"
                            alt="securety-image "
                            itemprop="logo"
                    />
                </div>
                <a
                        class="service-section__mobile"
                        href="{{store url='services/magento-security-audit'}}"
                >
                    <button type="button" class="service-section__mobile-button _button _button--arrow">
                        <span class="_button__text"> Discover more </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
            </div>
        </section>

        <section
                id="services-support-section"
                class="services-page__service-section service-section"
                itemscope
                itemtype="https://schema.org/Product"
        >
            <div class="service-section__body _grid-3-col">
                <div class="service-section__label _section-label" itemprop="keywords">Support</div>
                <div class="service-section__image">
                    <img loading="lazy" src="{{media url='wysiwyg/Service/support2.svg'}}" alt="support-image" itemprop="logo" />
                </div>
                <div class="service-section__content">
                    <h3 class="h3 service-section__title" itemprop="name">Magento Support</h3>
                    <div itemprop="description">
                        <p class="service-section__text">
                            We are an agency offering fully managed support and maintenance service for your business with 24/7
                            availability to ensure your online store improves and grows. Our support & maintenance offering is the
                            perfect way to scale your online business, specializing in Magento and offering a vast spectrum of
                            services.
                        </p>
                        <p class="service-section__text service-section__text--second-line">
                            It does not matter if you are from the United States, Australia, China, or Europe. We work with
                            different-sized eCommerce stores all over the globe.
                        </p>
                    </div>
                    <a href="{{store url='services/magento-support'}}">
                        <button type="button" class="service-section__button _button _button--arrow">
                            <span class="_button__text"> Discover more </span>
                            <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                            <span class="_button__overlay _button__overlay--hover"></span>
                            <span class="_button__overlay _button__overlay--active"></span>
                        </button>
                    </a>
                </div>
                <a
                        class="service-section__mobile"
                        href="{{store url='services/magento-support'}}"
                >

                    <button type="button" class="service-section__mobile-button _button _button--arrow">
                        <span class="_button__text"> Discover more </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
            </div>
        </section>

        <section
                id="services-optimization-section"
                class="services-page__service-section service-section"
                itemscope
                itemtype="https://schema.org/Product"
        >
            <div class="service-section__body _grid-3-col">
                <div class="service-section__label _section-label" itemprop="keywords">Optimization</div>
                <div class="service-section__content">
                    <h3 class="h3 service-section__title" itemprop="name">Server & Magento Optimization</h3>
                    <p class="service-section__text" itemprop="description">
                        Fix the low page load time & poor Core Web Vitals metrics for your business growth. Contact us to make the
                        best out of the Magento performance with the help of Adobe-certified experts.
                    </p>
                    <ul class="service-section__list">
                        <li>Website code improvements</li>
                        <li>Browser caching & render time boost</li>
                        <li>Extension data optimization</li>
                    </ul>
                    <a href="{{store url='services/server-optimization'}}">
                        <button type="button" class="service-section__button _button _button--arrow">
                            <span class="_button__text"> Discover more </span>
                            <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                            <span class="_button__overlay _button__overlay--hover"></span>
                            <span class="_button__overlay _button__overlay--active"></span>
                        </button>
                    </a>
                </div>
                <div class="service-section__image">
                    <img
                            loading="lazy"
                            src="{{media url='wysiwyg/Service/Frame.svg'}}"
                            alt="Magento Web Development"
                            itemprop="logo"
                    />
                </div>
                <a
                        class="service-section__mobile"
                        href="/services/server-optimization"
                >
                    <button type="button" class="service-section__mobile-button _button _button--arrow">
                        <span class="_button__text"> Discover more </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
            </div>
        </section>

        <section
                id="services-ga4-section"
                class="services-page__service-section service-section"
                itemscope
                itemtype="https://schema.org/Product"
        >
            <div class="service-section__body _grid-3-col">
                <div class="service-section__label _section-label" itemprop="keywords">Analytics</div>
                <div class="service-section__image">
                    <img src="{{media url='wysiwyg/Service/services-ga4.svg'}}" alt="analytics" itemprop="logo" />
                </div>
                <div class="service-section__content">
                    <h3 class="h3 service-section__title" itemprop="name">Implementation Google Analytics 4</h3>
                    <p class="service-section__text" itemprop="description">
                        If you are Magento merchant selling products online and striving to attract new customers or improve your
                        conversion rates, you need Google Analytics 4. It is the instrument to gather as much information as
                        possible about your customers' behavior from your website since it is the only layer between your customers
                        and your products.
                    </p>
                    <a href="{{store url='services/implementation-google-analytics-4-on-magento-2-with-gtm'}}">
                        <button type="button" class="service-section__button _button _button--arrow">
                            <span class="_button__text"> Discover more </span>
                            <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                            <span class="_button__overlay _button__overlay--hover"></span>
                            <span class="_button__overlay _button__overlay--active"></span>
                        </button>
                    </a>
                </div>
                <a
                        class="service-section__mobile"
                        href="{{store url='services/implementation-google-analytics-4-on-magento-2-with-gtm'}}"
                >
                    <button type="button" class="service-section__mobile-button _button _button--arrow">
                        <span class="_button__text"> Discover more </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
            </div>
        </section>
        <!--<section
    id="services-integration-section"
    class="services-page__service-section service-section"
    itemscope
    itemtype="https://schema.org/Product"
>
    <div class="service-section__body _grid-3-col">
        <div class="service-section__label _section-label" itemprop="keywords">Integration</div>
        <div class="service-section__content">
            <h3 class="h3 service-section__title" itemprop="name">Magento Integration</h3>
            <p class="service-section__text" itemprop="description">
                Integrate your Magento website with any backend system or external software to automate
                your work processes and execute your business strategy more efficiently
            </p>
            <ul class="service-section__list">
                <a href="{{store url='services/magento-integration'}}">
                    <button type="button" class="service-section__button _button _button--arrow">
                        <span class="_button__text"> Discover more </span>
                        <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                        <span class="_button__overlay _button__overlay--hover"></span>
                        <span class="_button__overlay _button__overlay--active"></span>
                    </button>
                </a>
        </div>
        <div class="service-section__image">
            <img
                loading="lazy"
                src="{{media url='wysiwyg/Service/magento-integration.svg'}}"
                alt="Magento Web Development"
                itemprop="logo"
            />
        </div>
        <a
            class="service-section__mobile"
            href="services/magento-integration"
        >
            <button type="button" class="service-section__mobile-button _button _button--arrow">
                <span class="_button__text"> Discover more </span>
                <span class="_button__text-overlay" style="clip: rect(0px, 0px, 24px, 0px)"> Discover more </span>
                <span class="_button__overlay _button__overlay--hover"></span>
                <span class="_button__overlay _button__overlay--active"></span>
            </button>
        </a>
    </div>
</section>-->
    </div>
</div>
