<style>
    @media screen and (max-width: 575px){
        .work-page__info--wmf{
            align-self: start;
            padding-left: 15px;
        }
    }
</style>
<div class="work-page">
    <div class="work-page__container _container">
        <h1 class="h2 work-page__title">
            best-in-class <br />
            eCommerce solutions
        </h1>
        <h2 class="h4 work-page__sub-title">
            Our passion lies in making complex things simple. We design and build websites,<br />
            e-commerce stores for some of the largest organisations in the world.
        </h2>

        <a class="work-page__row" href="/work/vodafone" target="_self">
            <div class="row__img work-page__image">
                <img loading="eager" src="{{media url='wysiwyg/work/vodafone_banner.png'}}" alt="Vodafone online store development" />
            </div>
            <div class="work-page__info">
                <h4 class="_h4">
                    Vodafone
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">
                    Online store of the leading mobile operator Vodafone Ukraine, which serves more than 19 million subscribers.
                </h5>
                <p class="work-page__small-text">Development, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>

        <a class="work-page__dual-top" href="https://www.ortlieb.com/" target="_blank">
            <div class="dual-top__img work-page__image">
                <img loading="eager" src="{{media url='wysiwyg/work/ortileb_banner.png'}}" alt="Ortlieb online store development" />
            </div>
            <div class="work-page__info">
                <h4 class="_h4">
                    Ortlieb
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">Online store of the the world’s leading brand of waterproof premium equipment.</h5>
                <p class="work-page__small-text">Development, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>

        <!-- Rowenta -->
        <a class="work-page__dual-bottom" href="/work/rowenta" target="_blank">
            <div class="dual-bottom__img work-page__image">
                <img loading="lazy" src="{{media url='wysiwyg/work/rowenta_banner.png'}}" alt="Rowenta online store development" />
            </div>
            <div class="work-page__info">
                <h4 class="_h4">
                    Rowenta
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">
                    Rowenta is a German manufacturer of small household appliances, founded in 1909.
                </h5>
                <p class="work-page__small-text">Development, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>

        <!-- Tefal -->
        <a class="work-page__row-reverse" href="/work/tefal" target="_self">
            <div class="row-reverse__img work-page__image">
                <img loading="lazy" src="{{media url='wysiwyg/work/tefal_banner.png'}}" alt="Tefal online store development" />
            </div>
            <div class="work-page__info">
                <h4 class="_h4">
                    Tefal
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">
                    Tefal is by your side to help you get the best out of every day in the simplest manner possible. With its
                    high-performance and easy-to-use innovations, Tefal helps you to seamlessly create a home full of life.
                </h5>
                <p class="work-page__small-text">Design, development, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>

        <!-- Krups -->
        <a class="work-page__dual-top-reverse" href="/work/krups" target="_self">
            <div class="dual-top-reverse__img work-page__image">
                <img loading="lazy" src="{{media url='wysiwyg/work/krups_banner.png'}}" alt="Krups online store development" />
            </div>
            <div class="work-page__info">
                <h4 class="_h4">
                    Krups
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">
                    Krups is a German kitchen appliance manufacturer known for its coffee makers, espresso machines, and other small household appliances.
                </h5>
                <p class="work-page__small-text">Design, development, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>

        <!-- Gardening Express -->
        <a class="work-page__dual-bottom-reverse" href="/work/gardening-express" target="_self">
            <div class="dual-bottom-reverse__img work-page__image">
                <img loading="lazy" src="{{media url='wysiwyg/taisiia-stupak-Kc4go4SRO3s-unsplash_1_min.png'}}" alt="Gardening Express Magento online store development" />
            </div>
            <div class="work-page__info">
                <h4 class="_h4">
                    Gardening Express
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">Gardening Express UK is a leading online retailer specializing in plants and garden accessories.</h5>
                <p class="work-page__small-text">Migration, server optimization, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>

        <!-- WMF -->
        <a class="work-page__row" href="/work/wmf" target="_self">
            <div class="row__img work-page__image">
                <img loading="lazy" src="{{media url='wysiwyg/work/wmf_banner.png'}}" alt="WMF online store development" />
            </div>
            <div class="work-page__info work-page__info--wmf">
                <h4 class="_h4">
                    WMF
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">
                    WMF is your ideal kitchen partner with over 160 years of tradition. Through products designed in Germany
                    boasting top-level functionalities and iconic design, WMF simplify and heighten the best moments in food
                    preparation, cooking and the sharing of dishes and beverages.
                </h5>
                <p class="work-page__small-text">Development, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>

        <!-- Aquapolis -->
        <a class="work-page__dual-top" href="/work/aquapolis" target="_self">
            <div class="dual-top__img work-page__image">
                <img loading="lazy" src="{{media url='wysiwyg/jamie-street-UnKbcMUjlIw-unsplash_1.png'}}" alt="Aquapolis ecommerce development" />
            </div>
            <div class="work-page__info">
                <h4 class="_h4">
                    Aquapolis
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">
                    Aquapolis.ua is a leading online store specializing in the sale of swimming pools and related equipment.
                </h5>
                <p class="work-page__small-text">Development, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>

        <!-- A-MANO Capri -->
        <a class="work-page__dual-bottom" href="/work/amano-capri" target="_self">
            <div class="dual-bottom__img work-page__image">
                <img loading="lazy" src="{{media url='wysiwyg/449884590_818868613293894_9126841631906027421_n_1.png'}}" alt="Chicco ecommerce development" />
            </div>
            <div class="work-page__info">
                <h4 class="_h4">
                    A•MANO Capri
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">
                    A•MANO Capri is a boutique in Capri, Italy that creates custom-fitted, handmade leather sandals using 3D printing technology.
                </h5>
                <p class="work-page__small-text">Development, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>

        <!-- GoodWine -->
        <a class="work-page__row-reverse work-page__last-item" href="/work/goodwine" target="_self">
            <div class="row-reverse__img work-page__image">
                <img loading="lazy" src="{{media url='wysiwyg/work/full-bottle-wine-with-copy-space_4_.png'}}" alt="ecommerce development for food delivery store" />
            </div>
            <div class="work-page__info">
                <h4 class="_h4">
                    Goodwine
                    <i class="work-page__link-mobile _link-www-icon _link-www-icon--mobile"></i>
                </h4>
                <h5 class="h5">
                    Good Wine is an importer and distributor of wine and strong spirits, founded in 2006. It has a retail network with two stores in Kyiv. The company is known for its organic, natural, and biodynamic products and wines from around the world.
                </h5>
                <p class="work-page__small-text">Development, integrations, support</p>
                <i class="work-page__link-desktop _link-www-icon"></i>
            </div>
        </a>
    </div>
</div>
